import type { AgentType } from "@agents-marketing/types";
import { agencyDeliveryPipeline } from "./agency-delivery.js";
import { adsWarriorPipeline } from "./ads-warrior.js";
import { crmLoyaltyPipeline } from "./crm-loyalty.js";
import { creativeStudioPipeline } from "./creative-studio.js";
import { ecommerceGrowthPipeline } from "./ecommerce-growth.js";
import { facebookGrowthPipeline } from "./facebook-growth.js";
import { funnelBuilderPipeline } from "./funnel-builder.js";
import { localGrowthPipeline } from "./local-growth.js";
import { membershipBuilderPipeline } from "./membership-builder.js";
import { paidMediaPipeline } from "./paid-media.js";
import { shopBuilderPipeline } from "./shop-builder.js";
import { socialAutomationPipeline } from "./social-automation.js";
import { socialEngagementPipeline } from "./social-engagement.js";
import { socialMonetizationPipeline } from "./social-monetization.js";
import type { AgentPipeline } from "./types.js";
import { voiceoverPipeline } from "./voiceover.js";
import { websiteBuilderPipeline } from "./website-builder.js";
import { websiteMultilangPipeline } from "./website-multilang.js";
export declare function getAgentPipeline<TAgentType extends AgentType>(agentType: TAgentType): AgentPipeline<TAgentType>;
export { creativeStudioPipeline, paidMediaPipeline, voiceoverPipeline, websiteBuilderPipeline, agencyDeliveryPipeline, adsWarriorPipeline, crmLoyaltyPipeline, ecommerceGrowthPipeline, facebookGrowthPipeline, funnelBuilderPipeline, localGrowthPipeline, membershipBuilderPipeline, shopBuilderPipeline, socialAutomationPipeline, socialEngagementPipeline, socialMonetizationPipeline, websiteMultilangPipeline };
export type { AgentPipeline, AgentPipelineContext, AgentPipelineResult, AgentPipelineStepDefinition } from "./types.js";
//# sourceMappingURL=index.d.ts.map