import { z } from "zod";
export declare const agentTypeSchema: z.ZodEnum<{
    creative_studio: "creative_studio";
    website_builder: "website_builder";
    voiceover: "voiceover";
    paid_media: "paid_media";
    website_multilang: "website_multilang";
    funnel_builder: "funnel_builder";
    agency_delivery: "agency_delivery";
    shop_builder: "shop_builder";
    ecommerce_growth: "ecommerce_growth";
    social_automation: "social_automation";
    facebook_growth: "facebook_growth";
    social_engagement: "social_engagement";
    social_monetization: "social_monetization";
    ads_warrior: "ads_warrior";
    crm_loyalty: "crm_loyalty";
    membership_builder: "membership_builder";
    local_growth: "local_growth";
}>;
export declare const projectStatusSchema: z.ZodEnum<{
    draft: "draft";
    active: "active";
    paused: "paused";
    completed: "completed";
    archived: "archived";
}>;
export declare const briefStatusSchema: z.ZodEnum<{
    archived: "archived";
    submitted: "submitted";
    parsed: "parsed";
    needs_clarification: "needs_clarification";
    approved: "approved";
}>;
export declare const jobStatusSchema: z.ZodEnum<{
    completed: "completed";
    queued: "queued";
    running: "running";
    failed: "failed";
    canceled: "canceled";
}>;
export declare const clientMemoryTypeSchema: z.ZodEnum<{
    fact: "fact";
    preference: "preference";
    constraint: "constraint";
    approved_copy: "approved_copy";
    approved_visual: "approved_visual";
}>;
export declare const clientMemoryEntrySchema: z.ZodObject<{
    id: z.ZodString;
    memoryType: z.ZodEnum<{
        fact: "fact";
        preference: "preference";
        constraint: "constraint";
        approved_copy: "approved_copy";
        approved_visual: "approved_visual";
    }>;
    key: z.ZodString;
    value: z.ZodUnknown;
    valueSummary: z.ZodString;
    source: z.ZodNullable<z.ZodString>;
    confidenceScore: z.ZodNullable<z.ZodNumber>;
}, z.core.$strip>;
export declare const clientBrandSnapshotSchema: z.ZodObject<{
    brandId: z.ZodNullable<z.ZodString>;
    brandName: z.ZodNullable<z.ZodString>;
    websiteUrl: z.ZodNullable<z.ZodString>;
    industry: z.ZodNullable<z.ZodString>;
    targetAudience: z.ZodNullable<z.ZodString>;
    toneOfVoice: z.ZodNullable<z.ZodString>;
    brandGuidelines: z.ZodNullable<z.ZodUnknown>;
}, z.core.$strip>;
export declare const clientMemoryContextSchema: z.ZodObject<{
    brand: z.ZodObject<{
        brandId: z.ZodNullable<z.ZodString>;
        brandName: z.ZodNullable<z.ZodString>;
        websiteUrl: z.ZodNullable<z.ZodString>;
        industry: z.ZodNullable<z.ZodString>;
        targetAudience: z.ZodNullable<z.ZodString>;
        toneOfVoice: z.ZodNullable<z.ZodString>;
        brandGuidelines: z.ZodNullable<z.ZodUnknown>;
    }, z.core.$strip>;
    facts: z.ZodDefault<z.ZodArray<z.ZodString>>;
    preferences: z.ZodDefault<z.ZodArray<z.ZodString>>;
    constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    approvedExamples: z.ZodDefault<z.ZodArray<z.ZodString>>;
    entries: z.ZodDefault<z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        memoryType: z.ZodEnum<{
            fact: "fact";
            preference: "preference";
            constraint: "constraint";
            approved_copy: "approved_copy";
            approved_visual: "approved_visual";
        }>;
        key: z.ZodString;
        value: z.ZodUnknown;
        valueSummary: z.ZodString;
        source: z.ZodNullable<z.ZodString>;
        confidenceScore: z.ZodNullable<z.ZodNumber>;
    }, z.core.$strip>>>;
}, z.core.$strip>;
export declare const creativeStudioDetailsSchema: z.ZodObject<{
    subject: z.ZodNullable<z.ZodString>;
    desiredStyle: z.ZodNullable<z.ZodString>;
    assetFormats: z.ZodDefault<z.ZodArray<z.ZodString>>;
    requestedFormats: z.ZodDefault<z.ZodArray<z.ZodString>>;
    visualDirections: z.ZodDefault<z.ZodArray<z.ZodString>>;
    copyToInclude: z.ZodDefault<z.ZodArray<z.ZodString>>;
    brandingColors: z.ZodDefault<z.ZodArray<z.ZodString>>;
    brandingNotes: z.ZodDefault<z.ZodArray<z.ZodString>>;
    logoRequested: z.ZodDefault<z.ZodBoolean>;
    deliverableCount: z.ZodNullable<z.ZodNumber>;
    visualReferences: z.ZodDefault<z.ZodArray<z.ZodString>>;
}, z.core.$strip>;
export declare const websiteBuilderDetailsSchema: z.ZodObject<{
    primaryCta: z.ZodNullable<z.ZodString>;
    requiredPages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    siteMapSections: z.ZodDefault<z.ZodArray<z.ZodString>>;
    technicalConstraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    siteType: z.ZodNullable<z.ZodString>;
    businessSector: z.ZodNullable<z.ZodString>;
    targetAudienceDescription: z.ZodNullable<z.ZodString>;
    existingContent: z.ZodDefault<z.ZodArray<z.ZodString>>;
    styleTone: z.ZodNullable<z.ZodString>;
}, z.core.$strip>;
export declare const voiceoverDetailsSchema: z.ZodObject<{
    language: z.ZodNullable<z.ZodString>;
    durationSeconds: z.ZodNullable<z.ZodNumber>;
    voiceStyle: z.ZodNullable<z.ZodString>;
    scriptConstraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    usage: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    messageSubject: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    desiredTone: z.ZodDefault<z.ZodNullable<z.ZodString>>;
}, z.core.$strip>;
export declare const paidMediaDetailsSchema: z.ZodObject<{
    offerOrProduct: z.ZodNullable<z.ZodString>;
    platforms: z.ZodDefault<z.ZodArray<z.ZodString>>;
    campaignObjective: z.ZodNullable<z.ZodString>;
    adFormats: z.ZodDefault<z.ZodArray<z.ZodString>>;
    audienceInsights: z.ZodDefault<z.ZodArray<z.ZodString>>;
    landingPageUrl: z.ZodNullable<z.ZodString>;
    testIdeas: z.ZodDefault<z.ZodArray<z.ZodString>>;
}, z.core.$strip>;
export declare const websiteMultilangDetailsSchema: z.ZodObject<{
    targetLanguages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    sourceLanguage: z.ZodNullable<z.ZodString>;
    siteType: z.ZodNullable<z.ZodString>;
    requiredPages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    seoLocalization: z.ZodDefault<z.ZodBoolean>;
    culturalAdaptation: z.ZodDefault<z.ZodBoolean>;
    technicalConstraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
}, z.core.$strip>;
export declare const funnelBuilderDetailsSchema: z.ZodObject<{
    funnelType: z.ZodNullable<z.ZodString>;
    offer: z.ZodNullable<z.ZodString>;
    stages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    primaryCta: z.ZodNullable<z.ZodString>;
    conversionGoal: z.ZodNullable<z.ZodString>;
    trafficSource: z.ZodDefault<z.ZodArray<z.ZodString>>;
    existingAssets: z.ZodDefault<z.ZodArray<z.ZodString>>;
}, z.core.$strip>;
export declare const agencyDeliveryDetailsSchema: z.ZodObject<{
    clientName: z.ZodNullable<z.ZodString>;
    projectScope: z.ZodNullable<z.ZodString>;
    deliverables: z.ZodDefault<z.ZodArray<z.ZodString>>;
    brandingIncluded: z.ZodDefault<z.ZodBoolean>;
    reportFormat: z.ZodNullable<z.ZodString>;
    presentationStyle: z.ZodNullable<z.ZodString>;
}, z.core.$strip>;
export declare const shopBuilderDetailsSchema: z.ZodObject<{
    shopType: z.ZodNullable<z.ZodString>;
    productCount: z.ZodNullable<z.ZodNumber>;
    categories: z.ZodDefault<z.ZodArray<z.ZodString>>;
    paymentMethods: z.ZodDefault<z.ZodArray<z.ZodString>>;
    shippingZones: z.ZodDefault<z.ZodArray<z.ZodString>>;
    technicalPlatform: z.ZodNullable<z.ZodString>;
    conversionOptimization: z.ZodDefault<z.ZodBoolean>;
}, z.core.$strip>;
export declare const ecommerceGrowthDetailsSchema: z.ZodObject<{
    products: z.ZodDefault<z.ZodArray<z.ZodString>>;
    targetKeywords: z.ZodDefault<z.ZodArray<z.ZodString>>;
    competitorUrls: z.ZodDefault<z.ZodArray<z.ZodString>>;
    growthLevers: z.ZodDefault<z.ZodArray<z.ZodString>>;
    currentRevenue: z.ZodNullable<z.ZodString>;
    targetRevenue: z.ZodNullable<z.ZodString>;
}, z.core.$strip>;
export declare const socialAutomationDetailsSchema: z.ZodObject<{
    platforms: z.ZodDefault<z.ZodArray<z.ZodString>>;
    postFrequency: z.ZodNullable<z.ZodString>;
    contentMix: z.ZodDefault<z.ZodArray<z.ZodString>>;
    hashtagStrategy: z.ZodDefault<z.ZodBoolean>;
    bestPostingTimes: z.ZodDefault<z.ZodBoolean>;
    calendarDays: z.ZodDefault<z.ZodNumber>;
}, z.core.$strip>;
export declare const facebookGrowthDetailsSchema: z.ZodObject<{
    pageType: z.ZodNullable<z.ZodString>;
    currentFollowers: z.ZodNullable<z.ZodNumber>;
    targetFollowers: z.ZodNullable<z.ZodNumber>;
    contentTypes: z.ZodDefault<z.ZodArray<z.ZodString>>;
    reelsStrategy: z.ZodDefault<z.ZodBoolean>;
    engagementTactics: z.ZodDefault<z.ZodArray<z.ZodString>>;
}, z.core.$strip>;
export declare const socialEngagementDetailsSchema: z.ZodObject<{
    platforms: z.ZodDefault<z.ZodArray<z.ZodString>>;
    commentTypes: z.ZodDefault<z.ZodArray<z.ZodString>>;
    responsePersona: z.ZodNullable<z.ZodString>;
    dmTemplates: z.ZodDefault<z.ZodBoolean>;
    escalationRules: z.ZodDefault<z.ZodArray<z.ZodString>>;
    brandVoice: z.ZodNullable<z.ZodString>;
}, z.core.$strip>;
export declare const socialMonetizationDetailsSchema: z.ZodObject<{
    platforms: z.ZodDefault<z.ZodArray<z.ZodString>>;
    audienceSize: z.ZodNullable<z.ZodString>;
    monetizationChannels: z.ZodDefault<z.ZodArray<z.ZodString>>;
    productIdeas: z.ZodDefault<z.ZodArray<z.ZodString>>;
    revenueTarget: z.ZodNullable<z.ZodString>;
    timeline: z.ZodNullable<z.ZodString>;
}, z.core.$strip>;
export declare const adsWarriorDetailsSchema: z.ZodObject<{
    platforms: z.ZodDefault<z.ZodArray<z.ZodString>>;
    totalBudget: z.ZodNullable<z.ZodString>;
    campaignObjectives: z.ZodDefault<z.ZodArray<z.ZodString>>;
    targetAudienceDetails: z.ZodDefault<z.ZodArray<z.ZodString>>;
    offerOrProduct: z.ZodNullable<z.ZodString>;
    existingCreatives: z.ZodDefault<z.ZodArray<z.ZodString>>;
    competitorAnalysis: z.ZodDefault<z.ZodBoolean>;
}, z.core.$strip>;
export declare const crmLoyaltyDetailsSchema: z.ZodObject<{
    programType: z.ZodNullable<z.ZodString>;
    customerSegments: z.ZodDefault<z.ZodArray<z.ZodString>>;
    rewardMechanisms: z.ZodDefault<z.ZodArray<z.ZodString>>;
    automationTriggers: z.ZodDefault<z.ZodArray<z.ZodString>>;
    retentionGoal: z.ZodNullable<z.ZodString>;
    currentChurnRate: z.ZodNullable<z.ZodString>;
}, z.core.$strip>;
export declare const membershipBuilderDetailsSchema: z.ZodObject<{
    membershipTiers: z.ZodDefault<z.ZodArray<z.ZodString>>;
    contentTypes: z.ZodDefault<z.ZodArray<z.ZodString>>;
    pricingModel: z.ZodNullable<z.ZodString>;
    platform: z.ZodNullable<z.ZodString>;
    onboardingFlow: z.ZodDefault<z.ZodBoolean>;
    communityFeatures: z.ZodDefault<z.ZodArray<z.ZodString>>;
}, z.core.$strip>;
export declare const localGrowthDetailsSchema: z.ZodObject<{
    businessType: z.ZodNullable<z.ZodString>;
    location: z.ZodNullable<z.ZodString>;
    radius: z.ZodNullable<z.ZodString>;
    acquisitionChannels: z.ZodDefault<z.ZodArray<z.ZodString>>;
    localSeoNeeded: z.ZodDefault<z.ZodBoolean>;
    googleMyBusiness: z.ZodDefault<z.ZodBoolean>;
    competitorAnalysis: z.ZodDefault<z.ZodBoolean>;
}, z.core.$strip>;
export declare const creativeStudioParsedBriefSchema: z.ZodObject<{
    title: z.ZodString;
    summary: z.ZodString;
    objectives: z.ZodArray<z.ZodString>;
    targetAudience: z.ZodDefault<z.ZodArray<z.ZodString>>;
    keyMessages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    deliverables: z.ZodDefault<z.ZodArray<z.ZodString>>;
    constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    references: z.ZodDefault<z.ZodArray<z.ZodString>>;
    tone: z.ZodNullable<z.ZodString>;
    callToAction: z.ZodNullable<z.ZodString>;
    locale: z.ZodNullable<z.ZodString>;
    budget: z.ZodNullable<z.ZodString>;
    timeline: z.ZodNullable<z.ZodString>;
    successMetrics: z.ZodDefault<z.ZodArray<z.ZodString>>;
    missingInformation: z.ZodDefault<z.ZodArray<z.ZodString>>;
    memoryContext: z.ZodObject<{
        brand: z.ZodObject<{
            brandId: z.ZodNullable<z.ZodString>;
            brandName: z.ZodNullable<z.ZodString>;
            websiteUrl: z.ZodNullable<z.ZodString>;
            industry: z.ZodNullable<z.ZodString>;
            targetAudience: z.ZodNullable<z.ZodString>;
            toneOfVoice: z.ZodNullable<z.ZodString>;
            brandGuidelines: z.ZodNullable<z.ZodUnknown>;
        }, z.core.$strip>;
        facts: z.ZodDefault<z.ZodArray<z.ZodString>>;
        preferences: z.ZodDefault<z.ZodArray<z.ZodString>>;
        constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
        approvedExamples: z.ZodDefault<z.ZodArray<z.ZodString>>;
        entries: z.ZodDefault<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            memoryType: z.ZodEnum<{
                fact: "fact";
                preference: "preference";
                constraint: "constraint";
                approved_copy: "approved_copy";
                approved_visual: "approved_visual";
            }>;
            key: z.ZodString;
            value: z.ZodUnknown;
            valueSummary: z.ZodString;
            source: z.ZodNullable<z.ZodString>;
            confidenceScore: z.ZodNullable<z.ZodNumber>;
        }, z.core.$strip>>>;
    }, z.core.$strip>;
    agentType: z.ZodLiteral<"creative_studio">;
    agentDetails: z.ZodObject<{
        subject: z.ZodNullable<z.ZodString>;
        desiredStyle: z.ZodNullable<z.ZodString>;
        assetFormats: z.ZodDefault<z.ZodArray<z.ZodString>>;
        requestedFormats: z.ZodDefault<z.ZodArray<z.ZodString>>;
        visualDirections: z.ZodDefault<z.ZodArray<z.ZodString>>;
        copyToInclude: z.ZodDefault<z.ZodArray<z.ZodString>>;
        brandingColors: z.ZodDefault<z.ZodArray<z.ZodString>>;
        brandingNotes: z.ZodDefault<z.ZodArray<z.ZodString>>;
        logoRequested: z.ZodDefault<z.ZodBoolean>;
        deliverableCount: z.ZodNullable<z.ZodNumber>;
        visualReferences: z.ZodDefault<z.ZodArray<z.ZodString>>;
    }, z.core.$strip>;
}, z.core.$strip>;
export declare const websiteBuilderParsedBriefSchema: z.ZodObject<{
    title: z.ZodString;
    summary: z.ZodString;
    objectives: z.ZodArray<z.ZodString>;
    targetAudience: z.ZodDefault<z.ZodArray<z.ZodString>>;
    keyMessages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    deliverables: z.ZodDefault<z.ZodArray<z.ZodString>>;
    constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    references: z.ZodDefault<z.ZodArray<z.ZodString>>;
    tone: z.ZodNullable<z.ZodString>;
    callToAction: z.ZodNullable<z.ZodString>;
    locale: z.ZodNullable<z.ZodString>;
    budget: z.ZodNullable<z.ZodString>;
    timeline: z.ZodNullable<z.ZodString>;
    successMetrics: z.ZodDefault<z.ZodArray<z.ZodString>>;
    missingInformation: z.ZodDefault<z.ZodArray<z.ZodString>>;
    memoryContext: z.ZodObject<{
        brand: z.ZodObject<{
            brandId: z.ZodNullable<z.ZodString>;
            brandName: z.ZodNullable<z.ZodString>;
            websiteUrl: z.ZodNullable<z.ZodString>;
            industry: z.ZodNullable<z.ZodString>;
            targetAudience: z.ZodNullable<z.ZodString>;
            toneOfVoice: z.ZodNullable<z.ZodString>;
            brandGuidelines: z.ZodNullable<z.ZodUnknown>;
        }, z.core.$strip>;
        facts: z.ZodDefault<z.ZodArray<z.ZodString>>;
        preferences: z.ZodDefault<z.ZodArray<z.ZodString>>;
        constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
        approvedExamples: z.ZodDefault<z.ZodArray<z.ZodString>>;
        entries: z.ZodDefault<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            memoryType: z.ZodEnum<{
                fact: "fact";
                preference: "preference";
                constraint: "constraint";
                approved_copy: "approved_copy";
                approved_visual: "approved_visual";
            }>;
            key: z.ZodString;
            value: z.ZodUnknown;
            valueSummary: z.ZodString;
            source: z.ZodNullable<z.ZodString>;
            confidenceScore: z.ZodNullable<z.ZodNumber>;
        }, z.core.$strip>>>;
    }, z.core.$strip>;
    agentType: z.ZodLiteral<"website_builder">;
    agentDetails: z.ZodObject<{
        primaryCta: z.ZodNullable<z.ZodString>;
        requiredPages: z.ZodDefault<z.ZodArray<z.ZodString>>;
        siteMapSections: z.ZodDefault<z.ZodArray<z.ZodString>>;
        technicalConstraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
        siteType: z.ZodNullable<z.ZodString>;
        businessSector: z.ZodNullable<z.ZodString>;
        targetAudienceDescription: z.ZodNullable<z.ZodString>;
        existingContent: z.ZodDefault<z.ZodArray<z.ZodString>>;
        styleTone: z.ZodNullable<z.ZodString>;
    }, z.core.$strip>;
}, z.core.$strip>;
export declare const voiceoverParsedBriefSchema: z.ZodObject<{
    title: z.ZodString;
    summary: z.ZodString;
    objectives: z.ZodArray<z.ZodString>;
    targetAudience: z.ZodDefault<z.ZodArray<z.ZodString>>;
    keyMessages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    deliverables: z.ZodDefault<z.ZodArray<z.ZodString>>;
    constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    references: z.ZodDefault<z.ZodArray<z.ZodString>>;
    tone: z.ZodNullable<z.ZodString>;
    callToAction: z.ZodNullable<z.ZodString>;
    locale: z.ZodNullable<z.ZodString>;
    budget: z.ZodNullable<z.ZodString>;
    timeline: z.ZodNullable<z.ZodString>;
    successMetrics: z.ZodDefault<z.ZodArray<z.ZodString>>;
    missingInformation: z.ZodDefault<z.ZodArray<z.ZodString>>;
    memoryContext: z.ZodObject<{
        brand: z.ZodObject<{
            brandId: z.ZodNullable<z.ZodString>;
            brandName: z.ZodNullable<z.ZodString>;
            websiteUrl: z.ZodNullable<z.ZodString>;
            industry: z.ZodNullable<z.ZodString>;
            targetAudience: z.ZodNullable<z.ZodString>;
            toneOfVoice: z.ZodNullable<z.ZodString>;
            brandGuidelines: z.ZodNullable<z.ZodUnknown>;
        }, z.core.$strip>;
        facts: z.ZodDefault<z.ZodArray<z.ZodString>>;
        preferences: z.ZodDefault<z.ZodArray<z.ZodString>>;
        constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
        approvedExamples: z.ZodDefault<z.ZodArray<z.ZodString>>;
        entries: z.ZodDefault<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            memoryType: z.ZodEnum<{
                fact: "fact";
                preference: "preference";
                constraint: "constraint";
                approved_copy: "approved_copy";
                approved_visual: "approved_visual";
            }>;
            key: z.ZodString;
            value: z.ZodUnknown;
            valueSummary: z.ZodString;
            source: z.ZodNullable<z.ZodString>;
            confidenceScore: z.ZodNullable<z.ZodNumber>;
        }, z.core.$strip>>>;
    }, z.core.$strip>;
    agentType: z.ZodLiteral<"voiceover">;
    agentDetails: z.ZodObject<{
        language: z.ZodNullable<z.ZodString>;
        durationSeconds: z.ZodNullable<z.ZodNumber>;
        voiceStyle: z.ZodNullable<z.ZodString>;
        scriptConstraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
        usage: z.ZodDefault<z.ZodNullable<z.ZodString>>;
        messageSubject: z.ZodDefault<z.ZodNullable<z.ZodString>>;
        desiredTone: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    }, z.core.$strip>;
}, z.core.$strip>;
export declare const paidMediaParsedBriefSchema: z.ZodObject<{
    title: z.ZodString;
    summary: z.ZodString;
    objectives: z.ZodArray<z.ZodString>;
    targetAudience: z.ZodDefault<z.ZodArray<z.ZodString>>;
    keyMessages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    deliverables: z.ZodDefault<z.ZodArray<z.ZodString>>;
    constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    references: z.ZodDefault<z.ZodArray<z.ZodString>>;
    tone: z.ZodNullable<z.ZodString>;
    callToAction: z.ZodNullable<z.ZodString>;
    locale: z.ZodNullable<z.ZodString>;
    budget: z.ZodNullable<z.ZodString>;
    timeline: z.ZodNullable<z.ZodString>;
    successMetrics: z.ZodDefault<z.ZodArray<z.ZodString>>;
    missingInformation: z.ZodDefault<z.ZodArray<z.ZodString>>;
    memoryContext: z.ZodObject<{
        brand: z.ZodObject<{
            brandId: z.ZodNullable<z.ZodString>;
            brandName: z.ZodNullable<z.ZodString>;
            websiteUrl: z.ZodNullable<z.ZodString>;
            industry: z.ZodNullable<z.ZodString>;
            targetAudience: z.ZodNullable<z.ZodString>;
            toneOfVoice: z.ZodNullable<z.ZodString>;
            brandGuidelines: z.ZodNullable<z.ZodUnknown>;
        }, z.core.$strip>;
        facts: z.ZodDefault<z.ZodArray<z.ZodString>>;
        preferences: z.ZodDefault<z.ZodArray<z.ZodString>>;
        constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
        approvedExamples: z.ZodDefault<z.ZodArray<z.ZodString>>;
        entries: z.ZodDefault<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            memoryType: z.ZodEnum<{
                fact: "fact";
                preference: "preference";
                constraint: "constraint";
                approved_copy: "approved_copy";
                approved_visual: "approved_visual";
            }>;
            key: z.ZodString;
            value: z.ZodUnknown;
            valueSummary: z.ZodString;
            source: z.ZodNullable<z.ZodString>;
            confidenceScore: z.ZodNullable<z.ZodNumber>;
        }, z.core.$strip>>>;
    }, z.core.$strip>;
    agentType: z.ZodLiteral<"paid_media">;
    agentDetails: z.ZodObject<{
        offerOrProduct: z.ZodNullable<z.ZodString>;
        platforms: z.ZodDefault<z.ZodArray<z.ZodString>>;
        campaignObjective: z.ZodNullable<z.ZodString>;
        adFormats: z.ZodDefault<z.ZodArray<z.ZodString>>;
        audienceInsights: z.ZodDefault<z.ZodArray<z.ZodString>>;
        landingPageUrl: z.ZodNullable<z.ZodString>;
        testIdeas: z.ZodDefault<z.ZodArray<z.ZodString>>;
    }, z.core.$strip>;
}, z.core.$strip>;
export declare const websiteMultilangParsedBriefSchema: z.ZodObject<{
    title: z.ZodString;
    summary: z.ZodString;
    objectives: z.ZodArray<z.ZodString>;
    targetAudience: z.ZodDefault<z.ZodArray<z.ZodString>>;
    keyMessages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    deliverables: z.ZodDefault<z.ZodArray<z.ZodString>>;
    constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    references: z.ZodDefault<z.ZodArray<z.ZodString>>;
    tone: z.ZodNullable<z.ZodString>;
    callToAction: z.ZodNullable<z.ZodString>;
    locale: z.ZodNullable<z.ZodString>;
    budget: z.ZodNullable<z.ZodString>;
    timeline: z.ZodNullable<z.ZodString>;
    successMetrics: z.ZodDefault<z.ZodArray<z.ZodString>>;
    missingInformation: z.ZodDefault<z.ZodArray<z.ZodString>>;
    memoryContext: z.ZodObject<{
        brand: z.ZodObject<{
            brandId: z.ZodNullable<z.ZodString>;
            brandName: z.ZodNullable<z.ZodString>;
            websiteUrl: z.ZodNullable<z.ZodString>;
            industry: z.ZodNullable<z.ZodString>;
            targetAudience: z.ZodNullable<z.ZodString>;
            toneOfVoice: z.ZodNullable<z.ZodString>;
            brandGuidelines: z.ZodNullable<z.ZodUnknown>;
        }, z.core.$strip>;
        facts: z.ZodDefault<z.ZodArray<z.ZodString>>;
        preferences: z.ZodDefault<z.ZodArray<z.ZodString>>;
        constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
        approvedExamples: z.ZodDefault<z.ZodArray<z.ZodString>>;
        entries: z.ZodDefault<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            memoryType: z.ZodEnum<{
                fact: "fact";
                preference: "preference";
                constraint: "constraint";
                approved_copy: "approved_copy";
                approved_visual: "approved_visual";
            }>;
            key: z.ZodString;
            value: z.ZodUnknown;
            valueSummary: z.ZodString;
            source: z.ZodNullable<z.ZodString>;
            confidenceScore: z.ZodNullable<z.ZodNumber>;
        }, z.core.$strip>>>;
    }, z.core.$strip>;
    agentType: z.ZodLiteral<"website_multilang">;
    agentDetails: z.ZodObject<{
        targetLanguages: z.ZodDefault<z.ZodArray<z.ZodString>>;
        sourceLanguage: z.ZodNullable<z.ZodString>;
        siteType: z.ZodNullable<z.ZodString>;
        requiredPages: z.ZodDefault<z.ZodArray<z.ZodString>>;
        seoLocalization: z.ZodDefault<z.ZodBoolean>;
        culturalAdaptation: z.ZodDefault<z.ZodBoolean>;
        technicalConstraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    }, z.core.$strip>;
}, z.core.$strip>;
export declare const funnelBuilderParsedBriefSchema: z.ZodObject<{
    title: z.ZodString;
    summary: z.ZodString;
    objectives: z.ZodArray<z.ZodString>;
    targetAudience: z.ZodDefault<z.ZodArray<z.ZodString>>;
    keyMessages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    deliverables: z.ZodDefault<z.ZodArray<z.ZodString>>;
    constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    references: z.ZodDefault<z.ZodArray<z.ZodString>>;
    tone: z.ZodNullable<z.ZodString>;
    callToAction: z.ZodNullable<z.ZodString>;
    locale: z.ZodNullable<z.ZodString>;
    budget: z.ZodNullable<z.ZodString>;
    timeline: z.ZodNullable<z.ZodString>;
    successMetrics: z.ZodDefault<z.ZodArray<z.ZodString>>;
    missingInformation: z.ZodDefault<z.ZodArray<z.ZodString>>;
    memoryContext: z.ZodObject<{
        brand: z.ZodObject<{
            brandId: z.ZodNullable<z.ZodString>;
            brandName: z.ZodNullable<z.ZodString>;
            websiteUrl: z.ZodNullable<z.ZodString>;
            industry: z.ZodNullable<z.ZodString>;
            targetAudience: z.ZodNullable<z.ZodString>;
            toneOfVoice: z.ZodNullable<z.ZodString>;
            brandGuidelines: z.ZodNullable<z.ZodUnknown>;
        }, z.core.$strip>;
        facts: z.ZodDefault<z.ZodArray<z.ZodString>>;
        preferences: z.ZodDefault<z.ZodArray<z.ZodString>>;
        constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
        approvedExamples: z.ZodDefault<z.ZodArray<z.ZodString>>;
        entries: z.ZodDefault<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            memoryType: z.ZodEnum<{
                fact: "fact";
                preference: "preference";
                constraint: "constraint";
                approved_copy: "approved_copy";
                approved_visual: "approved_visual";
            }>;
            key: z.ZodString;
            value: z.ZodUnknown;
            valueSummary: z.ZodString;
            source: z.ZodNullable<z.ZodString>;
            confidenceScore: z.ZodNullable<z.ZodNumber>;
        }, z.core.$strip>>>;
    }, z.core.$strip>;
    agentType: z.ZodLiteral<"funnel_builder">;
    agentDetails: z.ZodObject<{
        funnelType: z.ZodNullable<z.ZodString>;
        offer: z.ZodNullable<z.ZodString>;
        stages: z.ZodDefault<z.ZodArray<z.ZodString>>;
        primaryCta: z.ZodNullable<z.ZodString>;
        conversionGoal: z.ZodNullable<z.ZodString>;
        trafficSource: z.ZodDefault<z.ZodArray<z.ZodString>>;
        existingAssets: z.ZodDefault<z.ZodArray<z.ZodString>>;
    }, z.core.$strip>;
}, z.core.$strip>;
export declare const agencyDeliveryParsedBriefSchema: z.ZodObject<{
    title: z.ZodString;
    summary: z.ZodString;
    objectives: z.ZodArray<z.ZodString>;
    targetAudience: z.ZodDefault<z.ZodArray<z.ZodString>>;
    keyMessages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    deliverables: z.ZodDefault<z.ZodArray<z.ZodString>>;
    constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    references: z.ZodDefault<z.ZodArray<z.ZodString>>;
    tone: z.ZodNullable<z.ZodString>;
    callToAction: z.ZodNullable<z.ZodString>;
    locale: z.ZodNullable<z.ZodString>;
    budget: z.ZodNullable<z.ZodString>;
    timeline: z.ZodNullable<z.ZodString>;
    successMetrics: z.ZodDefault<z.ZodArray<z.ZodString>>;
    missingInformation: z.ZodDefault<z.ZodArray<z.ZodString>>;
    memoryContext: z.ZodObject<{
        brand: z.ZodObject<{
            brandId: z.ZodNullable<z.ZodString>;
            brandName: z.ZodNullable<z.ZodString>;
            websiteUrl: z.ZodNullable<z.ZodString>;
            industry: z.ZodNullable<z.ZodString>;
            targetAudience: z.ZodNullable<z.ZodString>;
            toneOfVoice: z.ZodNullable<z.ZodString>;
            brandGuidelines: z.ZodNullable<z.ZodUnknown>;
        }, z.core.$strip>;
        facts: z.ZodDefault<z.ZodArray<z.ZodString>>;
        preferences: z.ZodDefault<z.ZodArray<z.ZodString>>;
        constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
        approvedExamples: z.ZodDefault<z.ZodArray<z.ZodString>>;
        entries: z.ZodDefault<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            memoryType: z.ZodEnum<{
                fact: "fact";
                preference: "preference";
                constraint: "constraint";
                approved_copy: "approved_copy";
                approved_visual: "approved_visual";
            }>;
            key: z.ZodString;
            value: z.ZodUnknown;
            valueSummary: z.ZodString;
            source: z.ZodNullable<z.ZodString>;
            confidenceScore: z.ZodNullable<z.ZodNumber>;
        }, z.core.$strip>>>;
    }, z.core.$strip>;
    agentType: z.ZodLiteral<"agency_delivery">;
    agentDetails: z.ZodObject<{
        clientName: z.ZodNullable<z.ZodString>;
        projectScope: z.ZodNullable<z.ZodString>;
        deliverables: z.ZodDefault<z.ZodArray<z.ZodString>>;
        brandingIncluded: z.ZodDefault<z.ZodBoolean>;
        reportFormat: z.ZodNullable<z.ZodString>;
        presentationStyle: z.ZodNullable<z.ZodString>;
    }, z.core.$strip>;
}, z.core.$strip>;
export declare const shopBuilderParsedBriefSchema: z.ZodObject<{
    title: z.ZodString;
    summary: z.ZodString;
    objectives: z.ZodArray<z.ZodString>;
    targetAudience: z.ZodDefault<z.ZodArray<z.ZodString>>;
    keyMessages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    deliverables: z.ZodDefault<z.ZodArray<z.ZodString>>;
    constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    references: z.ZodDefault<z.ZodArray<z.ZodString>>;
    tone: z.ZodNullable<z.ZodString>;
    callToAction: z.ZodNullable<z.ZodString>;
    locale: z.ZodNullable<z.ZodString>;
    budget: z.ZodNullable<z.ZodString>;
    timeline: z.ZodNullable<z.ZodString>;
    successMetrics: z.ZodDefault<z.ZodArray<z.ZodString>>;
    missingInformation: z.ZodDefault<z.ZodArray<z.ZodString>>;
    memoryContext: z.ZodObject<{
        brand: z.ZodObject<{
            brandId: z.ZodNullable<z.ZodString>;
            brandName: z.ZodNullable<z.ZodString>;
            websiteUrl: z.ZodNullable<z.ZodString>;
            industry: z.ZodNullable<z.ZodString>;
            targetAudience: z.ZodNullable<z.ZodString>;
            toneOfVoice: z.ZodNullable<z.ZodString>;
            brandGuidelines: z.ZodNullable<z.ZodUnknown>;
        }, z.core.$strip>;
        facts: z.ZodDefault<z.ZodArray<z.ZodString>>;
        preferences: z.ZodDefault<z.ZodArray<z.ZodString>>;
        constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
        approvedExamples: z.ZodDefault<z.ZodArray<z.ZodString>>;
        entries: z.ZodDefault<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            memoryType: z.ZodEnum<{
                fact: "fact";
                preference: "preference";
                constraint: "constraint";
                approved_copy: "approved_copy";
                approved_visual: "approved_visual";
            }>;
            key: z.ZodString;
            value: z.ZodUnknown;
            valueSummary: z.ZodString;
            source: z.ZodNullable<z.ZodString>;
            confidenceScore: z.ZodNullable<z.ZodNumber>;
        }, z.core.$strip>>>;
    }, z.core.$strip>;
    agentType: z.ZodLiteral<"shop_builder">;
    agentDetails: z.ZodObject<{
        shopType: z.ZodNullable<z.ZodString>;
        productCount: z.ZodNullable<z.ZodNumber>;
        categories: z.ZodDefault<z.ZodArray<z.ZodString>>;
        paymentMethods: z.ZodDefault<z.ZodArray<z.ZodString>>;
        shippingZones: z.ZodDefault<z.ZodArray<z.ZodString>>;
        technicalPlatform: z.ZodNullable<z.ZodString>;
        conversionOptimization: z.ZodDefault<z.ZodBoolean>;
    }, z.core.$strip>;
}, z.core.$strip>;
export declare const ecommerceGrowthParsedBriefSchema: z.ZodObject<{
    title: z.ZodString;
    summary: z.ZodString;
    objectives: z.ZodArray<z.ZodString>;
    targetAudience: z.ZodDefault<z.ZodArray<z.ZodString>>;
    keyMessages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    deliverables: z.ZodDefault<z.ZodArray<z.ZodString>>;
    constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    references: z.ZodDefault<z.ZodArray<z.ZodString>>;
    tone: z.ZodNullable<z.ZodString>;
    callToAction: z.ZodNullable<z.ZodString>;
    locale: z.ZodNullable<z.ZodString>;
    budget: z.ZodNullable<z.ZodString>;
    timeline: z.ZodNullable<z.ZodString>;
    successMetrics: z.ZodDefault<z.ZodArray<z.ZodString>>;
    missingInformation: z.ZodDefault<z.ZodArray<z.ZodString>>;
    memoryContext: z.ZodObject<{
        brand: z.ZodObject<{
            brandId: z.ZodNullable<z.ZodString>;
            brandName: z.ZodNullable<z.ZodString>;
            websiteUrl: z.ZodNullable<z.ZodString>;
            industry: z.ZodNullable<z.ZodString>;
            targetAudience: z.ZodNullable<z.ZodString>;
            toneOfVoice: z.ZodNullable<z.ZodString>;
            brandGuidelines: z.ZodNullable<z.ZodUnknown>;
        }, z.core.$strip>;
        facts: z.ZodDefault<z.ZodArray<z.ZodString>>;
        preferences: z.ZodDefault<z.ZodArray<z.ZodString>>;
        constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
        approvedExamples: z.ZodDefault<z.ZodArray<z.ZodString>>;
        entries: z.ZodDefault<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            memoryType: z.ZodEnum<{
                fact: "fact";
                preference: "preference";
                constraint: "constraint";
                approved_copy: "approved_copy";
                approved_visual: "approved_visual";
            }>;
            key: z.ZodString;
            value: z.ZodUnknown;
            valueSummary: z.ZodString;
            source: z.ZodNullable<z.ZodString>;
            confidenceScore: z.ZodNullable<z.ZodNumber>;
        }, z.core.$strip>>>;
    }, z.core.$strip>;
    agentType: z.ZodLiteral<"ecommerce_growth">;
    agentDetails: z.ZodObject<{
        products: z.ZodDefault<z.ZodArray<z.ZodString>>;
        targetKeywords: z.ZodDefault<z.ZodArray<z.ZodString>>;
        competitorUrls: z.ZodDefault<z.ZodArray<z.ZodString>>;
        growthLevers: z.ZodDefault<z.ZodArray<z.ZodString>>;
        currentRevenue: z.ZodNullable<z.ZodString>;
        targetRevenue: z.ZodNullable<z.ZodString>;
    }, z.core.$strip>;
}, z.core.$strip>;
export declare const socialAutomationParsedBriefSchema: z.ZodObject<{
    title: z.ZodString;
    summary: z.ZodString;
    objectives: z.ZodArray<z.ZodString>;
    targetAudience: z.ZodDefault<z.ZodArray<z.ZodString>>;
    keyMessages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    deliverables: z.ZodDefault<z.ZodArray<z.ZodString>>;
    constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    references: z.ZodDefault<z.ZodArray<z.ZodString>>;
    tone: z.ZodNullable<z.ZodString>;
    callToAction: z.ZodNullable<z.ZodString>;
    locale: z.ZodNullable<z.ZodString>;
    budget: z.ZodNullable<z.ZodString>;
    timeline: z.ZodNullable<z.ZodString>;
    successMetrics: z.ZodDefault<z.ZodArray<z.ZodString>>;
    missingInformation: z.ZodDefault<z.ZodArray<z.ZodString>>;
    memoryContext: z.ZodObject<{
        brand: z.ZodObject<{
            brandId: z.ZodNullable<z.ZodString>;
            brandName: z.ZodNullable<z.ZodString>;
            websiteUrl: z.ZodNullable<z.ZodString>;
            industry: z.ZodNullable<z.ZodString>;
            targetAudience: z.ZodNullable<z.ZodString>;
            toneOfVoice: z.ZodNullable<z.ZodString>;
            brandGuidelines: z.ZodNullable<z.ZodUnknown>;
        }, z.core.$strip>;
        facts: z.ZodDefault<z.ZodArray<z.ZodString>>;
        preferences: z.ZodDefault<z.ZodArray<z.ZodString>>;
        constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
        approvedExamples: z.ZodDefault<z.ZodArray<z.ZodString>>;
        entries: z.ZodDefault<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            memoryType: z.ZodEnum<{
                fact: "fact";
                preference: "preference";
                constraint: "constraint";
                approved_copy: "approved_copy";
                approved_visual: "approved_visual";
            }>;
            key: z.ZodString;
            value: z.ZodUnknown;
            valueSummary: z.ZodString;
            source: z.ZodNullable<z.ZodString>;
            confidenceScore: z.ZodNullable<z.ZodNumber>;
        }, z.core.$strip>>>;
    }, z.core.$strip>;
    agentType: z.ZodLiteral<"social_automation">;
    agentDetails: z.ZodObject<{
        platforms: z.ZodDefault<z.ZodArray<z.ZodString>>;
        postFrequency: z.ZodNullable<z.ZodString>;
        contentMix: z.ZodDefault<z.ZodArray<z.ZodString>>;
        hashtagStrategy: z.ZodDefault<z.ZodBoolean>;
        bestPostingTimes: z.ZodDefault<z.ZodBoolean>;
        calendarDays: z.ZodDefault<z.ZodNumber>;
    }, z.core.$strip>;
}, z.core.$strip>;
export declare const facebookGrowthParsedBriefSchema: z.ZodObject<{
    title: z.ZodString;
    summary: z.ZodString;
    objectives: z.ZodArray<z.ZodString>;
    targetAudience: z.ZodDefault<z.ZodArray<z.ZodString>>;
    keyMessages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    deliverables: z.ZodDefault<z.ZodArray<z.ZodString>>;
    constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    references: z.ZodDefault<z.ZodArray<z.ZodString>>;
    tone: z.ZodNullable<z.ZodString>;
    callToAction: z.ZodNullable<z.ZodString>;
    locale: z.ZodNullable<z.ZodString>;
    budget: z.ZodNullable<z.ZodString>;
    timeline: z.ZodNullable<z.ZodString>;
    successMetrics: z.ZodDefault<z.ZodArray<z.ZodString>>;
    missingInformation: z.ZodDefault<z.ZodArray<z.ZodString>>;
    memoryContext: z.ZodObject<{
        brand: z.ZodObject<{
            brandId: z.ZodNullable<z.ZodString>;
            brandName: z.ZodNullable<z.ZodString>;
            websiteUrl: z.ZodNullable<z.ZodString>;
            industry: z.ZodNullable<z.ZodString>;
            targetAudience: z.ZodNullable<z.ZodString>;
            toneOfVoice: z.ZodNullable<z.ZodString>;
            brandGuidelines: z.ZodNullable<z.ZodUnknown>;
        }, z.core.$strip>;
        facts: z.ZodDefault<z.ZodArray<z.ZodString>>;
        preferences: z.ZodDefault<z.ZodArray<z.ZodString>>;
        constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
        approvedExamples: z.ZodDefault<z.ZodArray<z.ZodString>>;
        entries: z.ZodDefault<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            memoryType: z.ZodEnum<{
                fact: "fact";
                preference: "preference";
                constraint: "constraint";
                approved_copy: "approved_copy";
                approved_visual: "approved_visual";
            }>;
            key: z.ZodString;
            value: z.ZodUnknown;
            valueSummary: z.ZodString;
            source: z.ZodNullable<z.ZodString>;
            confidenceScore: z.ZodNullable<z.ZodNumber>;
        }, z.core.$strip>>>;
    }, z.core.$strip>;
    agentType: z.ZodLiteral<"facebook_growth">;
    agentDetails: z.ZodObject<{
        pageType: z.ZodNullable<z.ZodString>;
        currentFollowers: z.ZodNullable<z.ZodNumber>;
        targetFollowers: z.ZodNullable<z.ZodNumber>;
        contentTypes: z.ZodDefault<z.ZodArray<z.ZodString>>;
        reelsStrategy: z.ZodDefault<z.ZodBoolean>;
        engagementTactics: z.ZodDefault<z.ZodArray<z.ZodString>>;
    }, z.core.$strip>;
}, z.core.$strip>;
export declare const socialEngagementParsedBriefSchema: z.ZodObject<{
    title: z.ZodString;
    summary: z.ZodString;
    objectives: z.ZodArray<z.ZodString>;
    targetAudience: z.ZodDefault<z.ZodArray<z.ZodString>>;
    keyMessages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    deliverables: z.ZodDefault<z.ZodArray<z.ZodString>>;
    constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    references: z.ZodDefault<z.ZodArray<z.ZodString>>;
    tone: z.ZodNullable<z.ZodString>;
    callToAction: z.ZodNullable<z.ZodString>;
    locale: z.ZodNullable<z.ZodString>;
    budget: z.ZodNullable<z.ZodString>;
    timeline: z.ZodNullable<z.ZodString>;
    successMetrics: z.ZodDefault<z.ZodArray<z.ZodString>>;
    missingInformation: z.ZodDefault<z.ZodArray<z.ZodString>>;
    memoryContext: z.ZodObject<{
        brand: z.ZodObject<{
            brandId: z.ZodNullable<z.ZodString>;
            brandName: z.ZodNullable<z.ZodString>;
            websiteUrl: z.ZodNullable<z.ZodString>;
            industry: z.ZodNullable<z.ZodString>;
            targetAudience: z.ZodNullable<z.ZodString>;
            toneOfVoice: z.ZodNullable<z.ZodString>;
            brandGuidelines: z.ZodNullable<z.ZodUnknown>;
        }, z.core.$strip>;
        facts: z.ZodDefault<z.ZodArray<z.ZodString>>;
        preferences: z.ZodDefault<z.ZodArray<z.ZodString>>;
        constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
        approvedExamples: z.ZodDefault<z.ZodArray<z.ZodString>>;
        entries: z.ZodDefault<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            memoryType: z.ZodEnum<{
                fact: "fact";
                preference: "preference";
                constraint: "constraint";
                approved_copy: "approved_copy";
                approved_visual: "approved_visual";
            }>;
            key: z.ZodString;
            value: z.ZodUnknown;
            valueSummary: z.ZodString;
            source: z.ZodNullable<z.ZodString>;
            confidenceScore: z.ZodNullable<z.ZodNumber>;
        }, z.core.$strip>>>;
    }, z.core.$strip>;
    agentType: z.ZodLiteral<"social_engagement">;
    agentDetails: z.ZodObject<{
        platforms: z.ZodDefault<z.ZodArray<z.ZodString>>;
        commentTypes: z.ZodDefault<z.ZodArray<z.ZodString>>;
        responsePersona: z.ZodNullable<z.ZodString>;
        dmTemplates: z.ZodDefault<z.ZodBoolean>;
        escalationRules: z.ZodDefault<z.ZodArray<z.ZodString>>;
        brandVoice: z.ZodNullable<z.ZodString>;
    }, z.core.$strip>;
}, z.core.$strip>;
export declare const socialMonetizationParsedBriefSchema: z.ZodObject<{
    title: z.ZodString;
    summary: z.ZodString;
    objectives: z.ZodArray<z.ZodString>;
    targetAudience: z.ZodDefault<z.ZodArray<z.ZodString>>;
    keyMessages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    deliverables: z.ZodDefault<z.ZodArray<z.ZodString>>;
    constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    references: z.ZodDefault<z.ZodArray<z.ZodString>>;
    tone: z.ZodNullable<z.ZodString>;
    callToAction: z.ZodNullable<z.ZodString>;
    locale: z.ZodNullable<z.ZodString>;
    budget: z.ZodNullable<z.ZodString>;
    timeline: z.ZodNullable<z.ZodString>;
    successMetrics: z.ZodDefault<z.ZodArray<z.ZodString>>;
    missingInformation: z.ZodDefault<z.ZodArray<z.ZodString>>;
    memoryContext: z.ZodObject<{
        brand: z.ZodObject<{
            brandId: z.ZodNullable<z.ZodString>;
            brandName: z.ZodNullable<z.ZodString>;
            websiteUrl: z.ZodNullable<z.ZodString>;
            industry: z.ZodNullable<z.ZodString>;
            targetAudience: z.ZodNullable<z.ZodString>;
            toneOfVoice: z.ZodNullable<z.ZodString>;
            brandGuidelines: z.ZodNullable<z.ZodUnknown>;
        }, z.core.$strip>;
        facts: z.ZodDefault<z.ZodArray<z.ZodString>>;
        preferences: z.ZodDefault<z.ZodArray<z.ZodString>>;
        constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
        approvedExamples: z.ZodDefault<z.ZodArray<z.ZodString>>;
        entries: z.ZodDefault<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            memoryType: z.ZodEnum<{
                fact: "fact";
                preference: "preference";
                constraint: "constraint";
                approved_copy: "approved_copy";
                approved_visual: "approved_visual";
            }>;
            key: z.ZodString;
            value: z.ZodUnknown;
            valueSummary: z.ZodString;
            source: z.ZodNullable<z.ZodString>;
            confidenceScore: z.ZodNullable<z.ZodNumber>;
        }, z.core.$strip>>>;
    }, z.core.$strip>;
    agentType: z.ZodLiteral<"social_monetization">;
    agentDetails: z.ZodObject<{
        platforms: z.ZodDefault<z.ZodArray<z.ZodString>>;
        audienceSize: z.ZodNullable<z.ZodString>;
        monetizationChannels: z.ZodDefault<z.ZodArray<z.ZodString>>;
        productIdeas: z.ZodDefault<z.ZodArray<z.ZodString>>;
        revenueTarget: z.ZodNullable<z.ZodString>;
        timeline: z.ZodNullable<z.ZodString>;
    }, z.core.$strip>;
}, z.core.$strip>;
export declare const adsWarriorParsedBriefSchema: z.ZodObject<{
    title: z.ZodString;
    summary: z.ZodString;
    objectives: z.ZodArray<z.ZodString>;
    targetAudience: z.ZodDefault<z.ZodArray<z.ZodString>>;
    keyMessages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    deliverables: z.ZodDefault<z.ZodArray<z.ZodString>>;
    constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    references: z.ZodDefault<z.ZodArray<z.ZodString>>;
    tone: z.ZodNullable<z.ZodString>;
    callToAction: z.ZodNullable<z.ZodString>;
    locale: z.ZodNullable<z.ZodString>;
    budget: z.ZodNullable<z.ZodString>;
    timeline: z.ZodNullable<z.ZodString>;
    successMetrics: z.ZodDefault<z.ZodArray<z.ZodString>>;
    missingInformation: z.ZodDefault<z.ZodArray<z.ZodString>>;
    memoryContext: z.ZodObject<{
        brand: z.ZodObject<{
            brandId: z.ZodNullable<z.ZodString>;
            brandName: z.ZodNullable<z.ZodString>;
            websiteUrl: z.ZodNullable<z.ZodString>;
            industry: z.ZodNullable<z.ZodString>;
            targetAudience: z.ZodNullable<z.ZodString>;
            toneOfVoice: z.ZodNullable<z.ZodString>;
            brandGuidelines: z.ZodNullable<z.ZodUnknown>;
        }, z.core.$strip>;
        facts: z.ZodDefault<z.ZodArray<z.ZodString>>;
        preferences: z.ZodDefault<z.ZodArray<z.ZodString>>;
        constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
        approvedExamples: z.ZodDefault<z.ZodArray<z.ZodString>>;
        entries: z.ZodDefault<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            memoryType: z.ZodEnum<{
                fact: "fact";
                preference: "preference";
                constraint: "constraint";
                approved_copy: "approved_copy";
                approved_visual: "approved_visual";
            }>;
            key: z.ZodString;
            value: z.ZodUnknown;
            valueSummary: z.ZodString;
            source: z.ZodNullable<z.ZodString>;
            confidenceScore: z.ZodNullable<z.ZodNumber>;
        }, z.core.$strip>>>;
    }, z.core.$strip>;
    agentType: z.ZodLiteral<"ads_warrior">;
    agentDetails: z.ZodObject<{
        platforms: z.ZodDefault<z.ZodArray<z.ZodString>>;
        totalBudget: z.ZodNullable<z.ZodString>;
        campaignObjectives: z.ZodDefault<z.ZodArray<z.ZodString>>;
        targetAudienceDetails: z.ZodDefault<z.ZodArray<z.ZodString>>;
        offerOrProduct: z.ZodNullable<z.ZodString>;
        existingCreatives: z.ZodDefault<z.ZodArray<z.ZodString>>;
        competitorAnalysis: z.ZodDefault<z.ZodBoolean>;
    }, z.core.$strip>;
}, z.core.$strip>;
export declare const crmLoyaltyParsedBriefSchema: z.ZodObject<{
    title: z.ZodString;
    summary: z.ZodString;
    objectives: z.ZodArray<z.ZodString>;
    targetAudience: z.ZodDefault<z.ZodArray<z.ZodString>>;
    keyMessages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    deliverables: z.ZodDefault<z.ZodArray<z.ZodString>>;
    constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    references: z.ZodDefault<z.ZodArray<z.ZodString>>;
    tone: z.ZodNullable<z.ZodString>;
    callToAction: z.ZodNullable<z.ZodString>;
    locale: z.ZodNullable<z.ZodString>;
    budget: z.ZodNullable<z.ZodString>;
    timeline: z.ZodNullable<z.ZodString>;
    successMetrics: z.ZodDefault<z.ZodArray<z.ZodString>>;
    missingInformation: z.ZodDefault<z.ZodArray<z.ZodString>>;
    memoryContext: z.ZodObject<{
        brand: z.ZodObject<{
            brandId: z.ZodNullable<z.ZodString>;
            brandName: z.ZodNullable<z.ZodString>;
            websiteUrl: z.ZodNullable<z.ZodString>;
            industry: z.ZodNullable<z.ZodString>;
            targetAudience: z.ZodNullable<z.ZodString>;
            toneOfVoice: z.ZodNullable<z.ZodString>;
            brandGuidelines: z.ZodNullable<z.ZodUnknown>;
        }, z.core.$strip>;
        facts: z.ZodDefault<z.ZodArray<z.ZodString>>;
        preferences: z.ZodDefault<z.ZodArray<z.ZodString>>;
        constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
        approvedExamples: z.ZodDefault<z.ZodArray<z.ZodString>>;
        entries: z.ZodDefault<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            memoryType: z.ZodEnum<{
                fact: "fact";
                preference: "preference";
                constraint: "constraint";
                approved_copy: "approved_copy";
                approved_visual: "approved_visual";
            }>;
            key: z.ZodString;
            value: z.ZodUnknown;
            valueSummary: z.ZodString;
            source: z.ZodNullable<z.ZodString>;
            confidenceScore: z.ZodNullable<z.ZodNumber>;
        }, z.core.$strip>>>;
    }, z.core.$strip>;
    agentType: z.ZodLiteral<"crm_loyalty">;
    agentDetails: z.ZodObject<{
        programType: z.ZodNullable<z.ZodString>;
        customerSegments: z.ZodDefault<z.ZodArray<z.ZodString>>;
        rewardMechanisms: z.ZodDefault<z.ZodArray<z.ZodString>>;
        automationTriggers: z.ZodDefault<z.ZodArray<z.ZodString>>;
        retentionGoal: z.ZodNullable<z.ZodString>;
        currentChurnRate: z.ZodNullable<z.ZodString>;
    }, z.core.$strip>;
}, z.core.$strip>;
export declare const membershipBuilderParsedBriefSchema: z.ZodObject<{
    title: z.ZodString;
    summary: z.ZodString;
    objectives: z.ZodArray<z.ZodString>;
    targetAudience: z.ZodDefault<z.ZodArray<z.ZodString>>;
    keyMessages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    deliverables: z.ZodDefault<z.ZodArray<z.ZodString>>;
    constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    references: z.ZodDefault<z.ZodArray<z.ZodString>>;
    tone: z.ZodNullable<z.ZodString>;
    callToAction: z.ZodNullable<z.ZodString>;
    locale: z.ZodNullable<z.ZodString>;
    budget: z.ZodNullable<z.ZodString>;
    timeline: z.ZodNullable<z.ZodString>;
    successMetrics: z.ZodDefault<z.ZodArray<z.ZodString>>;
    missingInformation: z.ZodDefault<z.ZodArray<z.ZodString>>;
    memoryContext: z.ZodObject<{
        brand: z.ZodObject<{
            brandId: z.ZodNullable<z.ZodString>;
            brandName: z.ZodNullable<z.ZodString>;
            websiteUrl: z.ZodNullable<z.ZodString>;
            industry: z.ZodNullable<z.ZodString>;
            targetAudience: z.ZodNullable<z.ZodString>;
            toneOfVoice: z.ZodNullable<z.ZodString>;
            brandGuidelines: z.ZodNullable<z.ZodUnknown>;
        }, z.core.$strip>;
        facts: z.ZodDefault<z.ZodArray<z.ZodString>>;
        preferences: z.ZodDefault<z.ZodArray<z.ZodString>>;
        constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
        approvedExamples: z.ZodDefault<z.ZodArray<z.ZodString>>;
        entries: z.ZodDefault<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            memoryType: z.ZodEnum<{
                fact: "fact";
                preference: "preference";
                constraint: "constraint";
                approved_copy: "approved_copy";
                approved_visual: "approved_visual";
            }>;
            key: z.ZodString;
            value: z.ZodUnknown;
            valueSummary: z.ZodString;
            source: z.ZodNullable<z.ZodString>;
            confidenceScore: z.ZodNullable<z.ZodNumber>;
        }, z.core.$strip>>>;
    }, z.core.$strip>;
    agentType: z.ZodLiteral<"membership_builder">;
    agentDetails: z.ZodObject<{
        membershipTiers: z.ZodDefault<z.ZodArray<z.ZodString>>;
        contentTypes: z.ZodDefault<z.ZodArray<z.ZodString>>;
        pricingModel: z.ZodNullable<z.ZodString>;
        platform: z.ZodNullable<z.ZodString>;
        onboardingFlow: z.ZodDefault<z.ZodBoolean>;
        communityFeatures: z.ZodDefault<z.ZodArray<z.ZodString>>;
    }, z.core.$strip>;
}, z.core.$strip>;
export declare const localGrowthParsedBriefSchema: z.ZodObject<{
    title: z.ZodString;
    summary: z.ZodString;
    objectives: z.ZodArray<z.ZodString>;
    targetAudience: z.ZodDefault<z.ZodArray<z.ZodString>>;
    keyMessages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    deliverables: z.ZodDefault<z.ZodArray<z.ZodString>>;
    constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    references: z.ZodDefault<z.ZodArray<z.ZodString>>;
    tone: z.ZodNullable<z.ZodString>;
    callToAction: z.ZodNullable<z.ZodString>;
    locale: z.ZodNullable<z.ZodString>;
    budget: z.ZodNullable<z.ZodString>;
    timeline: z.ZodNullable<z.ZodString>;
    successMetrics: z.ZodDefault<z.ZodArray<z.ZodString>>;
    missingInformation: z.ZodDefault<z.ZodArray<z.ZodString>>;
    memoryContext: z.ZodObject<{
        brand: z.ZodObject<{
            brandId: z.ZodNullable<z.ZodString>;
            brandName: z.ZodNullable<z.ZodString>;
            websiteUrl: z.ZodNullable<z.ZodString>;
            industry: z.ZodNullable<z.ZodString>;
            targetAudience: z.ZodNullable<z.ZodString>;
            toneOfVoice: z.ZodNullable<z.ZodString>;
            brandGuidelines: z.ZodNullable<z.ZodUnknown>;
        }, z.core.$strip>;
        facts: z.ZodDefault<z.ZodArray<z.ZodString>>;
        preferences: z.ZodDefault<z.ZodArray<z.ZodString>>;
        constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
        approvedExamples: z.ZodDefault<z.ZodArray<z.ZodString>>;
        entries: z.ZodDefault<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            memoryType: z.ZodEnum<{
                fact: "fact";
                preference: "preference";
                constraint: "constraint";
                approved_copy: "approved_copy";
                approved_visual: "approved_visual";
            }>;
            key: z.ZodString;
            value: z.ZodUnknown;
            valueSummary: z.ZodString;
            source: z.ZodNullable<z.ZodString>;
            confidenceScore: z.ZodNullable<z.ZodNumber>;
        }, z.core.$strip>>>;
    }, z.core.$strip>;
    agentType: z.ZodLiteral<"local_growth">;
    agentDetails: z.ZodObject<{
        businessType: z.ZodNullable<z.ZodString>;
        location: z.ZodNullable<z.ZodString>;
        radius: z.ZodNullable<z.ZodString>;
        acquisitionChannels: z.ZodDefault<z.ZodArray<z.ZodString>>;
        localSeoNeeded: z.ZodDefault<z.ZodBoolean>;
        googleMyBusiness: z.ZodDefault<z.ZodBoolean>;
        competitorAnalysis: z.ZodDefault<z.ZodBoolean>;
    }, z.core.$strip>;
}, z.core.$strip>;
export declare const parsedBriefSchema: z.ZodDiscriminatedUnion<[z.ZodObject<{
    title: z.ZodString;
    summary: z.ZodString;
    objectives: z.ZodArray<z.ZodString>;
    targetAudience: z.ZodDefault<z.ZodArray<z.ZodString>>;
    keyMessages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    deliverables: z.ZodDefault<z.ZodArray<z.ZodString>>;
    constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    references: z.ZodDefault<z.ZodArray<z.ZodString>>;
    tone: z.ZodNullable<z.ZodString>;
    callToAction: z.ZodNullable<z.ZodString>;
    locale: z.ZodNullable<z.ZodString>;
    budget: z.ZodNullable<z.ZodString>;
    timeline: z.ZodNullable<z.ZodString>;
    successMetrics: z.ZodDefault<z.ZodArray<z.ZodString>>;
    missingInformation: z.ZodDefault<z.ZodArray<z.ZodString>>;
    memoryContext: z.ZodObject<{
        brand: z.ZodObject<{
            brandId: z.ZodNullable<z.ZodString>;
            brandName: z.ZodNullable<z.ZodString>;
            websiteUrl: z.ZodNullable<z.ZodString>;
            industry: z.ZodNullable<z.ZodString>;
            targetAudience: z.ZodNullable<z.ZodString>;
            toneOfVoice: z.ZodNullable<z.ZodString>;
            brandGuidelines: z.ZodNullable<z.ZodUnknown>;
        }, z.core.$strip>;
        facts: z.ZodDefault<z.ZodArray<z.ZodString>>;
        preferences: z.ZodDefault<z.ZodArray<z.ZodString>>;
        constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
        approvedExamples: z.ZodDefault<z.ZodArray<z.ZodString>>;
        entries: z.ZodDefault<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            memoryType: z.ZodEnum<{
                fact: "fact";
                preference: "preference";
                constraint: "constraint";
                approved_copy: "approved_copy";
                approved_visual: "approved_visual";
            }>;
            key: z.ZodString;
            value: z.ZodUnknown;
            valueSummary: z.ZodString;
            source: z.ZodNullable<z.ZodString>;
            confidenceScore: z.ZodNullable<z.ZodNumber>;
        }, z.core.$strip>>>;
    }, z.core.$strip>;
    agentType: z.ZodLiteral<"creative_studio">;
    agentDetails: z.ZodObject<{
        subject: z.ZodNullable<z.ZodString>;
        desiredStyle: z.ZodNullable<z.ZodString>;
        assetFormats: z.ZodDefault<z.ZodArray<z.ZodString>>;
        requestedFormats: z.ZodDefault<z.ZodArray<z.ZodString>>;
        visualDirections: z.ZodDefault<z.ZodArray<z.ZodString>>;
        copyToInclude: z.ZodDefault<z.ZodArray<z.ZodString>>;
        brandingColors: z.ZodDefault<z.ZodArray<z.ZodString>>;
        brandingNotes: z.ZodDefault<z.ZodArray<z.ZodString>>;
        logoRequested: z.ZodDefault<z.ZodBoolean>;
        deliverableCount: z.ZodNullable<z.ZodNumber>;
        visualReferences: z.ZodDefault<z.ZodArray<z.ZodString>>;
    }, z.core.$strip>;
}, z.core.$strip>, z.ZodObject<{
    title: z.ZodString;
    summary: z.ZodString;
    objectives: z.ZodArray<z.ZodString>;
    targetAudience: z.ZodDefault<z.ZodArray<z.ZodString>>;
    keyMessages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    deliverables: z.ZodDefault<z.ZodArray<z.ZodString>>;
    constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    references: z.ZodDefault<z.ZodArray<z.ZodString>>;
    tone: z.ZodNullable<z.ZodString>;
    callToAction: z.ZodNullable<z.ZodString>;
    locale: z.ZodNullable<z.ZodString>;
    budget: z.ZodNullable<z.ZodString>;
    timeline: z.ZodNullable<z.ZodString>;
    successMetrics: z.ZodDefault<z.ZodArray<z.ZodString>>;
    missingInformation: z.ZodDefault<z.ZodArray<z.ZodString>>;
    memoryContext: z.ZodObject<{
        brand: z.ZodObject<{
            brandId: z.ZodNullable<z.ZodString>;
            brandName: z.ZodNullable<z.ZodString>;
            websiteUrl: z.ZodNullable<z.ZodString>;
            industry: z.ZodNullable<z.ZodString>;
            targetAudience: z.ZodNullable<z.ZodString>;
            toneOfVoice: z.ZodNullable<z.ZodString>;
            brandGuidelines: z.ZodNullable<z.ZodUnknown>;
        }, z.core.$strip>;
        facts: z.ZodDefault<z.ZodArray<z.ZodString>>;
        preferences: z.ZodDefault<z.ZodArray<z.ZodString>>;
        constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
        approvedExamples: z.ZodDefault<z.ZodArray<z.ZodString>>;
        entries: z.ZodDefault<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            memoryType: z.ZodEnum<{
                fact: "fact";
                preference: "preference";
                constraint: "constraint";
                approved_copy: "approved_copy";
                approved_visual: "approved_visual";
            }>;
            key: z.ZodString;
            value: z.ZodUnknown;
            valueSummary: z.ZodString;
            source: z.ZodNullable<z.ZodString>;
            confidenceScore: z.ZodNullable<z.ZodNumber>;
        }, z.core.$strip>>>;
    }, z.core.$strip>;
    agentType: z.ZodLiteral<"website_builder">;
    agentDetails: z.ZodObject<{
        primaryCta: z.ZodNullable<z.ZodString>;
        requiredPages: z.ZodDefault<z.ZodArray<z.ZodString>>;
        siteMapSections: z.ZodDefault<z.ZodArray<z.ZodString>>;
        technicalConstraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
        siteType: z.ZodNullable<z.ZodString>;
        businessSector: z.ZodNullable<z.ZodString>;
        targetAudienceDescription: z.ZodNullable<z.ZodString>;
        existingContent: z.ZodDefault<z.ZodArray<z.ZodString>>;
        styleTone: z.ZodNullable<z.ZodString>;
    }, z.core.$strip>;
}, z.core.$strip>, z.ZodObject<{
    title: z.ZodString;
    summary: z.ZodString;
    objectives: z.ZodArray<z.ZodString>;
    targetAudience: z.ZodDefault<z.ZodArray<z.ZodString>>;
    keyMessages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    deliverables: z.ZodDefault<z.ZodArray<z.ZodString>>;
    constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    references: z.ZodDefault<z.ZodArray<z.ZodString>>;
    tone: z.ZodNullable<z.ZodString>;
    callToAction: z.ZodNullable<z.ZodString>;
    locale: z.ZodNullable<z.ZodString>;
    budget: z.ZodNullable<z.ZodString>;
    timeline: z.ZodNullable<z.ZodString>;
    successMetrics: z.ZodDefault<z.ZodArray<z.ZodString>>;
    missingInformation: z.ZodDefault<z.ZodArray<z.ZodString>>;
    memoryContext: z.ZodObject<{
        brand: z.ZodObject<{
            brandId: z.ZodNullable<z.ZodString>;
            brandName: z.ZodNullable<z.ZodString>;
            websiteUrl: z.ZodNullable<z.ZodString>;
            industry: z.ZodNullable<z.ZodString>;
            targetAudience: z.ZodNullable<z.ZodString>;
            toneOfVoice: z.ZodNullable<z.ZodString>;
            brandGuidelines: z.ZodNullable<z.ZodUnknown>;
        }, z.core.$strip>;
        facts: z.ZodDefault<z.ZodArray<z.ZodString>>;
        preferences: z.ZodDefault<z.ZodArray<z.ZodString>>;
        constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
        approvedExamples: z.ZodDefault<z.ZodArray<z.ZodString>>;
        entries: z.ZodDefault<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            memoryType: z.ZodEnum<{
                fact: "fact";
                preference: "preference";
                constraint: "constraint";
                approved_copy: "approved_copy";
                approved_visual: "approved_visual";
            }>;
            key: z.ZodString;
            value: z.ZodUnknown;
            valueSummary: z.ZodString;
            source: z.ZodNullable<z.ZodString>;
            confidenceScore: z.ZodNullable<z.ZodNumber>;
        }, z.core.$strip>>>;
    }, z.core.$strip>;
    agentType: z.ZodLiteral<"voiceover">;
    agentDetails: z.ZodObject<{
        language: z.ZodNullable<z.ZodString>;
        durationSeconds: z.ZodNullable<z.ZodNumber>;
        voiceStyle: z.ZodNullable<z.ZodString>;
        scriptConstraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
        usage: z.ZodDefault<z.ZodNullable<z.ZodString>>;
        messageSubject: z.ZodDefault<z.ZodNullable<z.ZodString>>;
        desiredTone: z.ZodDefault<z.ZodNullable<z.ZodString>>;
    }, z.core.$strip>;
}, z.core.$strip>, z.ZodObject<{
    title: z.ZodString;
    summary: z.ZodString;
    objectives: z.ZodArray<z.ZodString>;
    targetAudience: z.ZodDefault<z.ZodArray<z.ZodString>>;
    keyMessages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    deliverables: z.ZodDefault<z.ZodArray<z.ZodString>>;
    constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    references: z.ZodDefault<z.ZodArray<z.ZodString>>;
    tone: z.ZodNullable<z.ZodString>;
    callToAction: z.ZodNullable<z.ZodString>;
    locale: z.ZodNullable<z.ZodString>;
    budget: z.ZodNullable<z.ZodString>;
    timeline: z.ZodNullable<z.ZodString>;
    successMetrics: z.ZodDefault<z.ZodArray<z.ZodString>>;
    missingInformation: z.ZodDefault<z.ZodArray<z.ZodString>>;
    memoryContext: z.ZodObject<{
        brand: z.ZodObject<{
            brandId: z.ZodNullable<z.ZodString>;
            brandName: z.ZodNullable<z.ZodString>;
            websiteUrl: z.ZodNullable<z.ZodString>;
            industry: z.ZodNullable<z.ZodString>;
            targetAudience: z.ZodNullable<z.ZodString>;
            toneOfVoice: z.ZodNullable<z.ZodString>;
            brandGuidelines: z.ZodNullable<z.ZodUnknown>;
        }, z.core.$strip>;
        facts: z.ZodDefault<z.ZodArray<z.ZodString>>;
        preferences: z.ZodDefault<z.ZodArray<z.ZodString>>;
        constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
        approvedExamples: z.ZodDefault<z.ZodArray<z.ZodString>>;
        entries: z.ZodDefault<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            memoryType: z.ZodEnum<{
                fact: "fact";
                preference: "preference";
                constraint: "constraint";
                approved_copy: "approved_copy";
                approved_visual: "approved_visual";
            }>;
            key: z.ZodString;
            value: z.ZodUnknown;
            valueSummary: z.ZodString;
            source: z.ZodNullable<z.ZodString>;
            confidenceScore: z.ZodNullable<z.ZodNumber>;
        }, z.core.$strip>>>;
    }, z.core.$strip>;
    agentType: z.ZodLiteral<"paid_media">;
    agentDetails: z.ZodObject<{
        offerOrProduct: z.ZodNullable<z.ZodString>;
        platforms: z.ZodDefault<z.ZodArray<z.ZodString>>;
        campaignObjective: z.ZodNullable<z.ZodString>;
        adFormats: z.ZodDefault<z.ZodArray<z.ZodString>>;
        audienceInsights: z.ZodDefault<z.ZodArray<z.ZodString>>;
        landingPageUrl: z.ZodNullable<z.ZodString>;
        testIdeas: z.ZodDefault<z.ZodArray<z.ZodString>>;
    }, z.core.$strip>;
}, z.core.$strip>, z.ZodObject<{
    title: z.ZodString;
    summary: z.ZodString;
    objectives: z.ZodArray<z.ZodString>;
    targetAudience: z.ZodDefault<z.ZodArray<z.ZodString>>;
    keyMessages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    deliverables: z.ZodDefault<z.ZodArray<z.ZodString>>;
    constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    references: z.ZodDefault<z.ZodArray<z.ZodString>>;
    tone: z.ZodNullable<z.ZodString>;
    callToAction: z.ZodNullable<z.ZodString>;
    locale: z.ZodNullable<z.ZodString>;
    budget: z.ZodNullable<z.ZodString>;
    timeline: z.ZodNullable<z.ZodString>;
    successMetrics: z.ZodDefault<z.ZodArray<z.ZodString>>;
    missingInformation: z.ZodDefault<z.ZodArray<z.ZodString>>;
    memoryContext: z.ZodObject<{
        brand: z.ZodObject<{
            brandId: z.ZodNullable<z.ZodString>;
            brandName: z.ZodNullable<z.ZodString>;
            websiteUrl: z.ZodNullable<z.ZodString>;
            industry: z.ZodNullable<z.ZodString>;
            targetAudience: z.ZodNullable<z.ZodString>;
            toneOfVoice: z.ZodNullable<z.ZodString>;
            brandGuidelines: z.ZodNullable<z.ZodUnknown>;
        }, z.core.$strip>;
        facts: z.ZodDefault<z.ZodArray<z.ZodString>>;
        preferences: z.ZodDefault<z.ZodArray<z.ZodString>>;
        constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
        approvedExamples: z.ZodDefault<z.ZodArray<z.ZodString>>;
        entries: z.ZodDefault<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            memoryType: z.ZodEnum<{
                fact: "fact";
                preference: "preference";
                constraint: "constraint";
                approved_copy: "approved_copy";
                approved_visual: "approved_visual";
            }>;
            key: z.ZodString;
            value: z.ZodUnknown;
            valueSummary: z.ZodString;
            source: z.ZodNullable<z.ZodString>;
            confidenceScore: z.ZodNullable<z.ZodNumber>;
        }, z.core.$strip>>>;
    }, z.core.$strip>;
    agentType: z.ZodLiteral<"website_multilang">;
    agentDetails: z.ZodObject<{
        targetLanguages: z.ZodDefault<z.ZodArray<z.ZodString>>;
        sourceLanguage: z.ZodNullable<z.ZodString>;
        siteType: z.ZodNullable<z.ZodString>;
        requiredPages: z.ZodDefault<z.ZodArray<z.ZodString>>;
        seoLocalization: z.ZodDefault<z.ZodBoolean>;
        culturalAdaptation: z.ZodDefault<z.ZodBoolean>;
        technicalConstraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    }, z.core.$strip>;
}, z.core.$strip>, z.ZodObject<{
    title: z.ZodString;
    summary: z.ZodString;
    objectives: z.ZodArray<z.ZodString>;
    targetAudience: z.ZodDefault<z.ZodArray<z.ZodString>>;
    keyMessages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    deliverables: z.ZodDefault<z.ZodArray<z.ZodString>>;
    constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    references: z.ZodDefault<z.ZodArray<z.ZodString>>;
    tone: z.ZodNullable<z.ZodString>;
    callToAction: z.ZodNullable<z.ZodString>;
    locale: z.ZodNullable<z.ZodString>;
    budget: z.ZodNullable<z.ZodString>;
    timeline: z.ZodNullable<z.ZodString>;
    successMetrics: z.ZodDefault<z.ZodArray<z.ZodString>>;
    missingInformation: z.ZodDefault<z.ZodArray<z.ZodString>>;
    memoryContext: z.ZodObject<{
        brand: z.ZodObject<{
            brandId: z.ZodNullable<z.ZodString>;
            brandName: z.ZodNullable<z.ZodString>;
            websiteUrl: z.ZodNullable<z.ZodString>;
            industry: z.ZodNullable<z.ZodString>;
            targetAudience: z.ZodNullable<z.ZodString>;
            toneOfVoice: z.ZodNullable<z.ZodString>;
            brandGuidelines: z.ZodNullable<z.ZodUnknown>;
        }, z.core.$strip>;
        facts: z.ZodDefault<z.ZodArray<z.ZodString>>;
        preferences: z.ZodDefault<z.ZodArray<z.ZodString>>;
        constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
        approvedExamples: z.ZodDefault<z.ZodArray<z.ZodString>>;
        entries: z.ZodDefault<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            memoryType: z.ZodEnum<{
                fact: "fact";
                preference: "preference";
                constraint: "constraint";
                approved_copy: "approved_copy";
                approved_visual: "approved_visual";
            }>;
            key: z.ZodString;
            value: z.ZodUnknown;
            valueSummary: z.ZodString;
            source: z.ZodNullable<z.ZodString>;
            confidenceScore: z.ZodNullable<z.ZodNumber>;
        }, z.core.$strip>>>;
    }, z.core.$strip>;
    agentType: z.ZodLiteral<"funnel_builder">;
    agentDetails: z.ZodObject<{
        funnelType: z.ZodNullable<z.ZodString>;
        offer: z.ZodNullable<z.ZodString>;
        stages: z.ZodDefault<z.ZodArray<z.ZodString>>;
        primaryCta: z.ZodNullable<z.ZodString>;
        conversionGoal: z.ZodNullable<z.ZodString>;
        trafficSource: z.ZodDefault<z.ZodArray<z.ZodString>>;
        existingAssets: z.ZodDefault<z.ZodArray<z.ZodString>>;
    }, z.core.$strip>;
}, z.core.$strip>, z.ZodObject<{
    title: z.ZodString;
    summary: z.ZodString;
    objectives: z.ZodArray<z.ZodString>;
    targetAudience: z.ZodDefault<z.ZodArray<z.ZodString>>;
    keyMessages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    deliverables: z.ZodDefault<z.ZodArray<z.ZodString>>;
    constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    references: z.ZodDefault<z.ZodArray<z.ZodString>>;
    tone: z.ZodNullable<z.ZodString>;
    callToAction: z.ZodNullable<z.ZodString>;
    locale: z.ZodNullable<z.ZodString>;
    budget: z.ZodNullable<z.ZodString>;
    timeline: z.ZodNullable<z.ZodString>;
    successMetrics: z.ZodDefault<z.ZodArray<z.ZodString>>;
    missingInformation: z.ZodDefault<z.ZodArray<z.ZodString>>;
    memoryContext: z.ZodObject<{
        brand: z.ZodObject<{
            brandId: z.ZodNullable<z.ZodString>;
            brandName: z.ZodNullable<z.ZodString>;
            websiteUrl: z.ZodNullable<z.ZodString>;
            industry: z.ZodNullable<z.ZodString>;
            targetAudience: z.ZodNullable<z.ZodString>;
            toneOfVoice: z.ZodNullable<z.ZodString>;
            brandGuidelines: z.ZodNullable<z.ZodUnknown>;
        }, z.core.$strip>;
        facts: z.ZodDefault<z.ZodArray<z.ZodString>>;
        preferences: z.ZodDefault<z.ZodArray<z.ZodString>>;
        constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
        approvedExamples: z.ZodDefault<z.ZodArray<z.ZodString>>;
        entries: z.ZodDefault<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            memoryType: z.ZodEnum<{
                fact: "fact";
                preference: "preference";
                constraint: "constraint";
                approved_copy: "approved_copy";
                approved_visual: "approved_visual";
            }>;
            key: z.ZodString;
            value: z.ZodUnknown;
            valueSummary: z.ZodString;
            source: z.ZodNullable<z.ZodString>;
            confidenceScore: z.ZodNullable<z.ZodNumber>;
        }, z.core.$strip>>>;
    }, z.core.$strip>;
    agentType: z.ZodLiteral<"agency_delivery">;
    agentDetails: z.ZodObject<{
        clientName: z.ZodNullable<z.ZodString>;
        projectScope: z.ZodNullable<z.ZodString>;
        deliverables: z.ZodDefault<z.ZodArray<z.ZodString>>;
        brandingIncluded: z.ZodDefault<z.ZodBoolean>;
        reportFormat: z.ZodNullable<z.ZodString>;
        presentationStyle: z.ZodNullable<z.ZodString>;
    }, z.core.$strip>;
}, z.core.$strip>, z.ZodObject<{
    title: z.ZodString;
    summary: z.ZodString;
    objectives: z.ZodArray<z.ZodString>;
    targetAudience: z.ZodDefault<z.ZodArray<z.ZodString>>;
    keyMessages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    deliverables: z.ZodDefault<z.ZodArray<z.ZodString>>;
    constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    references: z.ZodDefault<z.ZodArray<z.ZodString>>;
    tone: z.ZodNullable<z.ZodString>;
    callToAction: z.ZodNullable<z.ZodString>;
    locale: z.ZodNullable<z.ZodString>;
    budget: z.ZodNullable<z.ZodString>;
    timeline: z.ZodNullable<z.ZodString>;
    successMetrics: z.ZodDefault<z.ZodArray<z.ZodString>>;
    missingInformation: z.ZodDefault<z.ZodArray<z.ZodString>>;
    memoryContext: z.ZodObject<{
        brand: z.ZodObject<{
            brandId: z.ZodNullable<z.ZodString>;
            brandName: z.ZodNullable<z.ZodString>;
            websiteUrl: z.ZodNullable<z.ZodString>;
            industry: z.ZodNullable<z.ZodString>;
            targetAudience: z.ZodNullable<z.ZodString>;
            toneOfVoice: z.ZodNullable<z.ZodString>;
            brandGuidelines: z.ZodNullable<z.ZodUnknown>;
        }, z.core.$strip>;
        facts: z.ZodDefault<z.ZodArray<z.ZodString>>;
        preferences: z.ZodDefault<z.ZodArray<z.ZodString>>;
        constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
        approvedExamples: z.ZodDefault<z.ZodArray<z.ZodString>>;
        entries: z.ZodDefault<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            memoryType: z.ZodEnum<{
                fact: "fact";
                preference: "preference";
                constraint: "constraint";
                approved_copy: "approved_copy";
                approved_visual: "approved_visual";
            }>;
            key: z.ZodString;
            value: z.ZodUnknown;
            valueSummary: z.ZodString;
            source: z.ZodNullable<z.ZodString>;
            confidenceScore: z.ZodNullable<z.ZodNumber>;
        }, z.core.$strip>>>;
    }, z.core.$strip>;
    agentType: z.ZodLiteral<"shop_builder">;
    agentDetails: z.ZodObject<{
        shopType: z.ZodNullable<z.ZodString>;
        productCount: z.ZodNullable<z.ZodNumber>;
        categories: z.ZodDefault<z.ZodArray<z.ZodString>>;
        paymentMethods: z.ZodDefault<z.ZodArray<z.ZodString>>;
        shippingZones: z.ZodDefault<z.ZodArray<z.ZodString>>;
        technicalPlatform: z.ZodNullable<z.ZodString>;
        conversionOptimization: z.ZodDefault<z.ZodBoolean>;
    }, z.core.$strip>;
}, z.core.$strip>, z.ZodObject<{
    title: z.ZodString;
    summary: z.ZodString;
    objectives: z.ZodArray<z.ZodString>;
    targetAudience: z.ZodDefault<z.ZodArray<z.ZodString>>;
    keyMessages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    deliverables: z.ZodDefault<z.ZodArray<z.ZodString>>;
    constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    references: z.ZodDefault<z.ZodArray<z.ZodString>>;
    tone: z.ZodNullable<z.ZodString>;
    callToAction: z.ZodNullable<z.ZodString>;
    locale: z.ZodNullable<z.ZodString>;
    budget: z.ZodNullable<z.ZodString>;
    timeline: z.ZodNullable<z.ZodString>;
    successMetrics: z.ZodDefault<z.ZodArray<z.ZodString>>;
    missingInformation: z.ZodDefault<z.ZodArray<z.ZodString>>;
    memoryContext: z.ZodObject<{
        brand: z.ZodObject<{
            brandId: z.ZodNullable<z.ZodString>;
            brandName: z.ZodNullable<z.ZodString>;
            websiteUrl: z.ZodNullable<z.ZodString>;
            industry: z.ZodNullable<z.ZodString>;
            targetAudience: z.ZodNullable<z.ZodString>;
            toneOfVoice: z.ZodNullable<z.ZodString>;
            brandGuidelines: z.ZodNullable<z.ZodUnknown>;
        }, z.core.$strip>;
        facts: z.ZodDefault<z.ZodArray<z.ZodString>>;
        preferences: z.ZodDefault<z.ZodArray<z.ZodString>>;
        constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
        approvedExamples: z.ZodDefault<z.ZodArray<z.ZodString>>;
        entries: z.ZodDefault<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            memoryType: z.ZodEnum<{
                fact: "fact";
                preference: "preference";
                constraint: "constraint";
                approved_copy: "approved_copy";
                approved_visual: "approved_visual";
            }>;
            key: z.ZodString;
            value: z.ZodUnknown;
            valueSummary: z.ZodString;
            source: z.ZodNullable<z.ZodString>;
            confidenceScore: z.ZodNullable<z.ZodNumber>;
        }, z.core.$strip>>>;
    }, z.core.$strip>;
    agentType: z.ZodLiteral<"ecommerce_growth">;
    agentDetails: z.ZodObject<{
        products: z.ZodDefault<z.ZodArray<z.ZodString>>;
        targetKeywords: z.ZodDefault<z.ZodArray<z.ZodString>>;
        competitorUrls: z.ZodDefault<z.ZodArray<z.ZodString>>;
        growthLevers: z.ZodDefault<z.ZodArray<z.ZodString>>;
        currentRevenue: z.ZodNullable<z.ZodString>;
        targetRevenue: z.ZodNullable<z.ZodString>;
    }, z.core.$strip>;
}, z.core.$strip>, z.ZodObject<{
    title: z.ZodString;
    summary: z.ZodString;
    objectives: z.ZodArray<z.ZodString>;
    targetAudience: z.ZodDefault<z.ZodArray<z.ZodString>>;
    keyMessages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    deliverables: z.ZodDefault<z.ZodArray<z.ZodString>>;
    constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    references: z.ZodDefault<z.ZodArray<z.ZodString>>;
    tone: z.ZodNullable<z.ZodString>;
    callToAction: z.ZodNullable<z.ZodString>;
    locale: z.ZodNullable<z.ZodString>;
    budget: z.ZodNullable<z.ZodString>;
    timeline: z.ZodNullable<z.ZodString>;
    successMetrics: z.ZodDefault<z.ZodArray<z.ZodString>>;
    missingInformation: z.ZodDefault<z.ZodArray<z.ZodString>>;
    memoryContext: z.ZodObject<{
        brand: z.ZodObject<{
            brandId: z.ZodNullable<z.ZodString>;
            brandName: z.ZodNullable<z.ZodString>;
            websiteUrl: z.ZodNullable<z.ZodString>;
            industry: z.ZodNullable<z.ZodString>;
            targetAudience: z.ZodNullable<z.ZodString>;
            toneOfVoice: z.ZodNullable<z.ZodString>;
            brandGuidelines: z.ZodNullable<z.ZodUnknown>;
        }, z.core.$strip>;
        facts: z.ZodDefault<z.ZodArray<z.ZodString>>;
        preferences: z.ZodDefault<z.ZodArray<z.ZodString>>;
        constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
        approvedExamples: z.ZodDefault<z.ZodArray<z.ZodString>>;
        entries: z.ZodDefault<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            memoryType: z.ZodEnum<{
                fact: "fact";
                preference: "preference";
                constraint: "constraint";
                approved_copy: "approved_copy";
                approved_visual: "approved_visual";
            }>;
            key: z.ZodString;
            value: z.ZodUnknown;
            valueSummary: z.ZodString;
            source: z.ZodNullable<z.ZodString>;
            confidenceScore: z.ZodNullable<z.ZodNumber>;
        }, z.core.$strip>>>;
    }, z.core.$strip>;
    agentType: z.ZodLiteral<"social_automation">;
    agentDetails: z.ZodObject<{
        platforms: z.ZodDefault<z.ZodArray<z.ZodString>>;
        postFrequency: z.ZodNullable<z.ZodString>;
        contentMix: z.ZodDefault<z.ZodArray<z.ZodString>>;
        hashtagStrategy: z.ZodDefault<z.ZodBoolean>;
        bestPostingTimes: z.ZodDefault<z.ZodBoolean>;
        calendarDays: z.ZodDefault<z.ZodNumber>;
    }, z.core.$strip>;
}, z.core.$strip>, z.ZodObject<{
    title: z.ZodString;
    summary: z.ZodString;
    objectives: z.ZodArray<z.ZodString>;
    targetAudience: z.ZodDefault<z.ZodArray<z.ZodString>>;
    keyMessages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    deliverables: z.ZodDefault<z.ZodArray<z.ZodString>>;
    constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    references: z.ZodDefault<z.ZodArray<z.ZodString>>;
    tone: z.ZodNullable<z.ZodString>;
    callToAction: z.ZodNullable<z.ZodString>;
    locale: z.ZodNullable<z.ZodString>;
    budget: z.ZodNullable<z.ZodString>;
    timeline: z.ZodNullable<z.ZodString>;
    successMetrics: z.ZodDefault<z.ZodArray<z.ZodString>>;
    missingInformation: z.ZodDefault<z.ZodArray<z.ZodString>>;
    memoryContext: z.ZodObject<{
        brand: z.ZodObject<{
            brandId: z.ZodNullable<z.ZodString>;
            brandName: z.ZodNullable<z.ZodString>;
            websiteUrl: z.ZodNullable<z.ZodString>;
            industry: z.ZodNullable<z.ZodString>;
            targetAudience: z.ZodNullable<z.ZodString>;
            toneOfVoice: z.ZodNullable<z.ZodString>;
            brandGuidelines: z.ZodNullable<z.ZodUnknown>;
        }, z.core.$strip>;
        facts: z.ZodDefault<z.ZodArray<z.ZodString>>;
        preferences: z.ZodDefault<z.ZodArray<z.ZodString>>;
        constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
        approvedExamples: z.ZodDefault<z.ZodArray<z.ZodString>>;
        entries: z.ZodDefault<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            memoryType: z.ZodEnum<{
                fact: "fact";
                preference: "preference";
                constraint: "constraint";
                approved_copy: "approved_copy";
                approved_visual: "approved_visual";
            }>;
            key: z.ZodString;
            value: z.ZodUnknown;
            valueSummary: z.ZodString;
            source: z.ZodNullable<z.ZodString>;
            confidenceScore: z.ZodNullable<z.ZodNumber>;
        }, z.core.$strip>>>;
    }, z.core.$strip>;
    agentType: z.ZodLiteral<"facebook_growth">;
    agentDetails: z.ZodObject<{
        pageType: z.ZodNullable<z.ZodString>;
        currentFollowers: z.ZodNullable<z.ZodNumber>;
        targetFollowers: z.ZodNullable<z.ZodNumber>;
        contentTypes: z.ZodDefault<z.ZodArray<z.ZodString>>;
        reelsStrategy: z.ZodDefault<z.ZodBoolean>;
        engagementTactics: z.ZodDefault<z.ZodArray<z.ZodString>>;
    }, z.core.$strip>;
}, z.core.$strip>, z.ZodObject<{
    title: z.ZodString;
    summary: z.ZodString;
    objectives: z.ZodArray<z.ZodString>;
    targetAudience: z.ZodDefault<z.ZodArray<z.ZodString>>;
    keyMessages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    deliverables: z.ZodDefault<z.ZodArray<z.ZodString>>;
    constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    references: z.ZodDefault<z.ZodArray<z.ZodString>>;
    tone: z.ZodNullable<z.ZodString>;
    callToAction: z.ZodNullable<z.ZodString>;
    locale: z.ZodNullable<z.ZodString>;
    budget: z.ZodNullable<z.ZodString>;
    timeline: z.ZodNullable<z.ZodString>;
    successMetrics: z.ZodDefault<z.ZodArray<z.ZodString>>;
    missingInformation: z.ZodDefault<z.ZodArray<z.ZodString>>;
    memoryContext: z.ZodObject<{
        brand: z.ZodObject<{
            brandId: z.ZodNullable<z.ZodString>;
            brandName: z.ZodNullable<z.ZodString>;
            websiteUrl: z.ZodNullable<z.ZodString>;
            industry: z.ZodNullable<z.ZodString>;
            targetAudience: z.ZodNullable<z.ZodString>;
            toneOfVoice: z.ZodNullable<z.ZodString>;
            brandGuidelines: z.ZodNullable<z.ZodUnknown>;
        }, z.core.$strip>;
        facts: z.ZodDefault<z.ZodArray<z.ZodString>>;
        preferences: z.ZodDefault<z.ZodArray<z.ZodString>>;
        constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
        approvedExamples: z.ZodDefault<z.ZodArray<z.ZodString>>;
        entries: z.ZodDefault<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            memoryType: z.ZodEnum<{
                fact: "fact";
                preference: "preference";
                constraint: "constraint";
                approved_copy: "approved_copy";
                approved_visual: "approved_visual";
            }>;
            key: z.ZodString;
            value: z.ZodUnknown;
            valueSummary: z.ZodString;
            source: z.ZodNullable<z.ZodString>;
            confidenceScore: z.ZodNullable<z.ZodNumber>;
        }, z.core.$strip>>>;
    }, z.core.$strip>;
    agentType: z.ZodLiteral<"social_engagement">;
    agentDetails: z.ZodObject<{
        platforms: z.ZodDefault<z.ZodArray<z.ZodString>>;
        commentTypes: z.ZodDefault<z.ZodArray<z.ZodString>>;
        responsePersona: z.ZodNullable<z.ZodString>;
        dmTemplates: z.ZodDefault<z.ZodBoolean>;
        escalationRules: z.ZodDefault<z.ZodArray<z.ZodString>>;
        brandVoice: z.ZodNullable<z.ZodString>;
    }, z.core.$strip>;
}, z.core.$strip>, z.ZodObject<{
    title: z.ZodString;
    summary: z.ZodString;
    objectives: z.ZodArray<z.ZodString>;
    targetAudience: z.ZodDefault<z.ZodArray<z.ZodString>>;
    keyMessages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    deliverables: z.ZodDefault<z.ZodArray<z.ZodString>>;
    constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    references: z.ZodDefault<z.ZodArray<z.ZodString>>;
    tone: z.ZodNullable<z.ZodString>;
    callToAction: z.ZodNullable<z.ZodString>;
    locale: z.ZodNullable<z.ZodString>;
    budget: z.ZodNullable<z.ZodString>;
    timeline: z.ZodNullable<z.ZodString>;
    successMetrics: z.ZodDefault<z.ZodArray<z.ZodString>>;
    missingInformation: z.ZodDefault<z.ZodArray<z.ZodString>>;
    memoryContext: z.ZodObject<{
        brand: z.ZodObject<{
            brandId: z.ZodNullable<z.ZodString>;
            brandName: z.ZodNullable<z.ZodString>;
            websiteUrl: z.ZodNullable<z.ZodString>;
            industry: z.ZodNullable<z.ZodString>;
            targetAudience: z.ZodNullable<z.ZodString>;
            toneOfVoice: z.ZodNullable<z.ZodString>;
            brandGuidelines: z.ZodNullable<z.ZodUnknown>;
        }, z.core.$strip>;
        facts: z.ZodDefault<z.ZodArray<z.ZodString>>;
        preferences: z.ZodDefault<z.ZodArray<z.ZodString>>;
        constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
        approvedExamples: z.ZodDefault<z.ZodArray<z.ZodString>>;
        entries: z.ZodDefault<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            memoryType: z.ZodEnum<{
                fact: "fact";
                preference: "preference";
                constraint: "constraint";
                approved_copy: "approved_copy";
                approved_visual: "approved_visual";
            }>;
            key: z.ZodString;
            value: z.ZodUnknown;
            valueSummary: z.ZodString;
            source: z.ZodNullable<z.ZodString>;
            confidenceScore: z.ZodNullable<z.ZodNumber>;
        }, z.core.$strip>>>;
    }, z.core.$strip>;
    agentType: z.ZodLiteral<"social_monetization">;
    agentDetails: z.ZodObject<{
        platforms: z.ZodDefault<z.ZodArray<z.ZodString>>;
        audienceSize: z.ZodNullable<z.ZodString>;
        monetizationChannels: z.ZodDefault<z.ZodArray<z.ZodString>>;
        productIdeas: z.ZodDefault<z.ZodArray<z.ZodString>>;
        revenueTarget: z.ZodNullable<z.ZodString>;
        timeline: z.ZodNullable<z.ZodString>;
    }, z.core.$strip>;
}, z.core.$strip>, z.ZodObject<{
    title: z.ZodString;
    summary: z.ZodString;
    objectives: z.ZodArray<z.ZodString>;
    targetAudience: z.ZodDefault<z.ZodArray<z.ZodString>>;
    keyMessages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    deliverables: z.ZodDefault<z.ZodArray<z.ZodString>>;
    constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    references: z.ZodDefault<z.ZodArray<z.ZodString>>;
    tone: z.ZodNullable<z.ZodString>;
    callToAction: z.ZodNullable<z.ZodString>;
    locale: z.ZodNullable<z.ZodString>;
    budget: z.ZodNullable<z.ZodString>;
    timeline: z.ZodNullable<z.ZodString>;
    successMetrics: z.ZodDefault<z.ZodArray<z.ZodString>>;
    missingInformation: z.ZodDefault<z.ZodArray<z.ZodString>>;
    memoryContext: z.ZodObject<{
        brand: z.ZodObject<{
            brandId: z.ZodNullable<z.ZodString>;
            brandName: z.ZodNullable<z.ZodString>;
            websiteUrl: z.ZodNullable<z.ZodString>;
            industry: z.ZodNullable<z.ZodString>;
            targetAudience: z.ZodNullable<z.ZodString>;
            toneOfVoice: z.ZodNullable<z.ZodString>;
            brandGuidelines: z.ZodNullable<z.ZodUnknown>;
        }, z.core.$strip>;
        facts: z.ZodDefault<z.ZodArray<z.ZodString>>;
        preferences: z.ZodDefault<z.ZodArray<z.ZodString>>;
        constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
        approvedExamples: z.ZodDefault<z.ZodArray<z.ZodString>>;
        entries: z.ZodDefault<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            memoryType: z.ZodEnum<{
                fact: "fact";
                preference: "preference";
                constraint: "constraint";
                approved_copy: "approved_copy";
                approved_visual: "approved_visual";
            }>;
            key: z.ZodString;
            value: z.ZodUnknown;
            valueSummary: z.ZodString;
            source: z.ZodNullable<z.ZodString>;
            confidenceScore: z.ZodNullable<z.ZodNumber>;
        }, z.core.$strip>>>;
    }, z.core.$strip>;
    agentType: z.ZodLiteral<"ads_warrior">;
    agentDetails: z.ZodObject<{
        platforms: z.ZodDefault<z.ZodArray<z.ZodString>>;
        totalBudget: z.ZodNullable<z.ZodString>;
        campaignObjectives: z.ZodDefault<z.ZodArray<z.ZodString>>;
        targetAudienceDetails: z.ZodDefault<z.ZodArray<z.ZodString>>;
        offerOrProduct: z.ZodNullable<z.ZodString>;
        existingCreatives: z.ZodDefault<z.ZodArray<z.ZodString>>;
        competitorAnalysis: z.ZodDefault<z.ZodBoolean>;
    }, z.core.$strip>;
}, z.core.$strip>, z.ZodObject<{
    title: z.ZodString;
    summary: z.ZodString;
    objectives: z.ZodArray<z.ZodString>;
    targetAudience: z.ZodDefault<z.ZodArray<z.ZodString>>;
    keyMessages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    deliverables: z.ZodDefault<z.ZodArray<z.ZodString>>;
    constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    references: z.ZodDefault<z.ZodArray<z.ZodString>>;
    tone: z.ZodNullable<z.ZodString>;
    callToAction: z.ZodNullable<z.ZodString>;
    locale: z.ZodNullable<z.ZodString>;
    budget: z.ZodNullable<z.ZodString>;
    timeline: z.ZodNullable<z.ZodString>;
    successMetrics: z.ZodDefault<z.ZodArray<z.ZodString>>;
    missingInformation: z.ZodDefault<z.ZodArray<z.ZodString>>;
    memoryContext: z.ZodObject<{
        brand: z.ZodObject<{
            brandId: z.ZodNullable<z.ZodString>;
            brandName: z.ZodNullable<z.ZodString>;
            websiteUrl: z.ZodNullable<z.ZodString>;
            industry: z.ZodNullable<z.ZodString>;
            targetAudience: z.ZodNullable<z.ZodString>;
            toneOfVoice: z.ZodNullable<z.ZodString>;
            brandGuidelines: z.ZodNullable<z.ZodUnknown>;
        }, z.core.$strip>;
        facts: z.ZodDefault<z.ZodArray<z.ZodString>>;
        preferences: z.ZodDefault<z.ZodArray<z.ZodString>>;
        constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
        approvedExamples: z.ZodDefault<z.ZodArray<z.ZodString>>;
        entries: z.ZodDefault<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            memoryType: z.ZodEnum<{
                fact: "fact";
                preference: "preference";
                constraint: "constraint";
                approved_copy: "approved_copy";
                approved_visual: "approved_visual";
            }>;
            key: z.ZodString;
            value: z.ZodUnknown;
            valueSummary: z.ZodString;
            source: z.ZodNullable<z.ZodString>;
            confidenceScore: z.ZodNullable<z.ZodNumber>;
        }, z.core.$strip>>>;
    }, z.core.$strip>;
    agentType: z.ZodLiteral<"crm_loyalty">;
    agentDetails: z.ZodObject<{
        programType: z.ZodNullable<z.ZodString>;
        customerSegments: z.ZodDefault<z.ZodArray<z.ZodString>>;
        rewardMechanisms: z.ZodDefault<z.ZodArray<z.ZodString>>;
        automationTriggers: z.ZodDefault<z.ZodArray<z.ZodString>>;
        retentionGoal: z.ZodNullable<z.ZodString>;
        currentChurnRate: z.ZodNullable<z.ZodString>;
    }, z.core.$strip>;
}, z.core.$strip>, z.ZodObject<{
    title: z.ZodString;
    summary: z.ZodString;
    objectives: z.ZodArray<z.ZodString>;
    targetAudience: z.ZodDefault<z.ZodArray<z.ZodString>>;
    keyMessages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    deliverables: z.ZodDefault<z.ZodArray<z.ZodString>>;
    constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    references: z.ZodDefault<z.ZodArray<z.ZodString>>;
    tone: z.ZodNullable<z.ZodString>;
    callToAction: z.ZodNullable<z.ZodString>;
    locale: z.ZodNullable<z.ZodString>;
    budget: z.ZodNullable<z.ZodString>;
    timeline: z.ZodNullable<z.ZodString>;
    successMetrics: z.ZodDefault<z.ZodArray<z.ZodString>>;
    missingInformation: z.ZodDefault<z.ZodArray<z.ZodString>>;
    memoryContext: z.ZodObject<{
        brand: z.ZodObject<{
            brandId: z.ZodNullable<z.ZodString>;
            brandName: z.ZodNullable<z.ZodString>;
            websiteUrl: z.ZodNullable<z.ZodString>;
            industry: z.ZodNullable<z.ZodString>;
            targetAudience: z.ZodNullable<z.ZodString>;
            toneOfVoice: z.ZodNullable<z.ZodString>;
            brandGuidelines: z.ZodNullable<z.ZodUnknown>;
        }, z.core.$strip>;
        facts: z.ZodDefault<z.ZodArray<z.ZodString>>;
        preferences: z.ZodDefault<z.ZodArray<z.ZodString>>;
        constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
        approvedExamples: z.ZodDefault<z.ZodArray<z.ZodString>>;
        entries: z.ZodDefault<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            memoryType: z.ZodEnum<{
                fact: "fact";
                preference: "preference";
                constraint: "constraint";
                approved_copy: "approved_copy";
                approved_visual: "approved_visual";
            }>;
            key: z.ZodString;
            value: z.ZodUnknown;
            valueSummary: z.ZodString;
            source: z.ZodNullable<z.ZodString>;
            confidenceScore: z.ZodNullable<z.ZodNumber>;
        }, z.core.$strip>>>;
    }, z.core.$strip>;
    agentType: z.ZodLiteral<"membership_builder">;
    agentDetails: z.ZodObject<{
        membershipTiers: z.ZodDefault<z.ZodArray<z.ZodString>>;
        contentTypes: z.ZodDefault<z.ZodArray<z.ZodString>>;
        pricingModel: z.ZodNullable<z.ZodString>;
        platform: z.ZodNullable<z.ZodString>;
        onboardingFlow: z.ZodDefault<z.ZodBoolean>;
        communityFeatures: z.ZodDefault<z.ZodArray<z.ZodString>>;
    }, z.core.$strip>;
}, z.core.$strip>, z.ZodObject<{
    title: z.ZodString;
    summary: z.ZodString;
    objectives: z.ZodArray<z.ZodString>;
    targetAudience: z.ZodDefault<z.ZodArray<z.ZodString>>;
    keyMessages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    deliverables: z.ZodDefault<z.ZodArray<z.ZodString>>;
    constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
    references: z.ZodDefault<z.ZodArray<z.ZodString>>;
    tone: z.ZodNullable<z.ZodString>;
    callToAction: z.ZodNullable<z.ZodString>;
    locale: z.ZodNullable<z.ZodString>;
    budget: z.ZodNullable<z.ZodString>;
    timeline: z.ZodNullable<z.ZodString>;
    successMetrics: z.ZodDefault<z.ZodArray<z.ZodString>>;
    missingInformation: z.ZodDefault<z.ZodArray<z.ZodString>>;
    memoryContext: z.ZodObject<{
        brand: z.ZodObject<{
            brandId: z.ZodNullable<z.ZodString>;
            brandName: z.ZodNullable<z.ZodString>;
            websiteUrl: z.ZodNullable<z.ZodString>;
            industry: z.ZodNullable<z.ZodString>;
            targetAudience: z.ZodNullable<z.ZodString>;
            toneOfVoice: z.ZodNullable<z.ZodString>;
            brandGuidelines: z.ZodNullable<z.ZodUnknown>;
        }, z.core.$strip>;
        facts: z.ZodDefault<z.ZodArray<z.ZodString>>;
        preferences: z.ZodDefault<z.ZodArray<z.ZodString>>;
        constraints: z.ZodDefault<z.ZodArray<z.ZodString>>;
        approvedExamples: z.ZodDefault<z.ZodArray<z.ZodString>>;
        entries: z.ZodDefault<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            memoryType: z.ZodEnum<{
                fact: "fact";
                preference: "preference";
                constraint: "constraint";
                approved_copy: "approved_copy";
                approved_visual: "approved_visual";
            }>;
            key: z.ZodString;
            value: z.ZodUnknown;
            valueSummary: z.ZodString;
            source: z.ZodNullable<z.ZodString>;
            confidenceScore: z.ZodNullable<z.ZodNumber>;
        }, z.core.$strip>>>;
    }, z.core.$strip>;
    agentType: z.ZodLiteral<"local_growth">;
    agentDetails: z.ZodObject<{
        businessType: z.ZodNullable<z.ZodString>;
        location: z.ZodNullable<z.ZodString>;
        radius: z.ZodNullable<z.ZodString>;
        acquisitionChannels: z.ZodDefault<z.ZodArray<z.ZodString>>;
        localSeoNeeded: z.ZodDefault<z.ZodBoolean>;
        googleMyBusiness: z.ZodDefault<z.ZodBoolean>;
        competitorAnalysis: z.ZodDefault<z.ZodBoolean>;
    }, z.core.$strip>;
}, z.core.$strip>], "agentType">;
export declare const workflowJobPayloadSchema: z.ZodObject<{
    jobId: z.ZodString;
    agentType: z.ZodEnum<{
        creative_studio: "creative_studio";
        website_builder: "website_builder";
        voiceover: "voiceover";
        paid_media: "paid_media";
        website_multilang: "website_multilang";
        funnel_builder: "funnel_builder";
        agency_delivery: "agency_delivery";
        shop_builder: "shop_builder";
        ecommerce_growth: "ecommerce_growth";
        social_automation: "social_automation";
        facebook_growth: "facebook_growth";
        social_engagement: "social_engagement";
        social_monetization: "social_monetization";
        ads_warrior: "ads_warrior";
        crm_loyalty: "crm_loyalty";
        membership_builder: "membership_builder";
        local_growth: "local_growth";
    }>;
}, z.core.$strip>;
export type AgentType = z.infer<typeof agentTypeSchema>;
export type ProjectStatus = z.infer<typeof projectStatusSchema>;
export type BriefStatus = z.infer<typeof briefStatusSchema>;
export type JobStatus = z.infer<typeof jobStatusSchema>;
export type ClientMemoryType = z.infer<typeof clientMemoryTypeSchema>;
export type ClientMemoryEntry = z.infer<typeof clientMemoryEntrySchema>;
export type ClientMemoryContext = z.infer<typeof clientMemoryContextSchema>;
export type ParsedBriefJson = z.infer<typeof parsedBriefSchema>;
export type ParsedBriefByAgentType<TAgentType extends AgentType> = Extract<ParsedBriefJson, {
    agentType: TAgentType;
}>;
export type WorkflowJobPayload = z.infer<typeof workflowJobPayloadSchema>;
//# sourceMappingURL=index.d.ts.map